### ISSUE TITLE
Bubid error

### ISSUE THREAD

**Issue by lgldl** [tianweiy/CenterPoint#1]
while we build the CenterPoint, the error occured , which is as follows:
nuScenes devkit not found!
nuScenes devkit not Found!

we have add the python path export PYTHONPATH="${PYTHONPATH}:/home/lgl/3D_object_detection/CenterPoint/nuscenes-devkit/python-sdk" to ~/.bashrc and reactivate bash, but it doesn't seem to be working.

**Comment by tianweiy** [comment]
What do you get if you simply import nuscenes in the python shell?

**Comment by tianweiy** [comment]
nuscenes-devkit are just some python files. And it doesn't need any setup after it is added into the python path.

**Comment by lgldl** [comment]
> nuscenes-devkit are just some python files. And it doesn't need any setup after it is added into the python path.

Thank you four your reply. There was also a problem running the demo. I have download the demo.zip and last.path. while I run the demo, the error occured, it seems the data is wrong.

nuScenes devkit not found!
nuScenes devkit not Found!
Use HM Bias:  -2.19
10
Traceback (most recent call last):
  File "/home/lgl/3D_object_detection/CenterPoint/tools/demo.py", line 128, in <module>
    main()
  File "/home/lgl/3D_object_detection/CenterPoint/tools/demo.py", line 82, in main
    for i, data_batch in enumerate(data_loader):
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lgl/anaconda3/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lgl/3D_object_detection/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 184, in __getitem__
    return self.get_sensor_data(idx)
  File "/home/lgl/3D_object_detection/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 179, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/home/lgl/3D_object_detection/CenterPoint/det3d/datasets/pipelines/compose.py", line 25, in __call__
    res, info = t(res, info)
  File "/home/lgl/3D_object_detection/CenterPoint/det3d/datasets/pipelines/loading.py", line 85, in __call__
    sweep_times_list = [np.zeros((points.shape[0], 1))]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by tianweiy** [comment]
Hi, I think the path is not correct. is the demo folder in the main directory of CenterPoint?

**Comment by tianweiy** [comment]
this is a read error in the line 25~32 of "/home/lgl/3D_object_detection/CenterPoint/det3d/datasets/pipelines/loading.py"". And the only reason I can imaging is that there is not a lidar file at the path.

**Comment by tianweiy** [comment]
you can add a print statement at line 28 to see the path and check if there is a file there

**Comment by tianweiy** [comment]
close for now. Feel free to reopen if you still have questions.
