### ISSUE TITLE
how do I train in single gpu

### ISSUE THREAD

**Issue by wj-shin** [tianweiy/CenterPoint#106]
Hi, tianweiy 

Thank you for centerpoint.

But I have some problem when I train centerpoint.

I have only one gpu. So I want to learn with single gpu. Can you give me Guideline?
Additionally, the following error occurred and I would appreciate your advice on how to solve it.

Thank you

(centerpoint) ------@------:~/------/cp/CenterPoint$ python -m torch.distributed.launch --nproc_per_node=1 ./tools/train.py /home/------/------/cp/CenterPoint/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py
2021-03-30 17:11:55.051995: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
No Tensorflow
Deformable Convolution not built!
2021-03-30 17:11:55,117 - INFO - Distributed training: False
2021-03-30 17:11:55,117 - INFO - torch.backends.cudnn.benchmark: False
2021-03-30 17:11:55,139 - INFO - Finish RPN Initialization
2021-03-30 17:11:55,139 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
2021-03-30 17:11:55,164 - INFO - Finish CenterHead Initialization
Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 112, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/------/------/cp/CenterPoint/det3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/------/------/cp/CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/home/-----/------/cp/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 45, in __init__
    super(NuScenesDataset, self).__init__(
  File "/home/------/------/cp/CenterPoint/det3d/datasets/custom.py", line 37, in __init__
    self._set_group_flag()
  File "/home/------/------/cp/CenterPoint/det3d/datasets/custom.py", line 164, in _set_group_flag
    self.flag = np.ones(len(self), dtype=np.uint8)
  File "/home/------/------/cp/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 121, in __len__
    self.load_infos(self._info_path)
  File "/home/-----/------/cp/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 89, in load_infos
    _cls_dist = {k: len(v) / duplicated_samples for k, v in _cls_infos.items()}
  File "/home/------/------/cp/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 89, in <dictcomp>
    _cls_dist = {k: len(v) / duplicated_samples for k, v in _cls_infos.items()}
ZeroDivisionError: division by zero
Killing subprocess 10506
Traceback (most recent call last):
  File "/home/------/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/------/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/------/anaconda3/envs/centerpoint/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/-----/------/envs/centerpoint/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/-----/anaconda3/envs/centerpoint/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/-----/anaconda3/envs/centerpoint/bin/python', '-u', './tools/train.py', '--local_rank=0', '/home/------/------/cp/CenterPoint/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py']' returned non-zero exit status 1.

I modified some to  --- because  I don`t want to be known my private impormation(like name and name of laboratory)
and I use cuda 11.0 and pytorch 1.8.1 cudnn 8.5.0 

and install apex and spconv by your guideline (install.md)

**Comment by tianweiy** [comment]
this is not related to gpu. Is this nuScenes mini ?

**Comment by tianweiy** [comment]
change this line https://github.com/tianweiy/CenterPoint/blob/046e1e0e8cdaa2168bc4ac0bf1ad052a0cd58294/det3d/datasets/nuscenes/nuscenes.py#L89 to 


```
            _cls_dist = {k: len(v) / max(duplicated_samples, 1) for k, v in _cls_infos.items()}
```

**Comment by wj-shin** [comment]
here is the night because I live in Asia.

I will proceed with your proposal after 8 to 9 hours.

Can you stay awake and help me then?(If this expression is rude, very very sorry...I'm poor at english...)

I used a data set already stored in our lab.

Could you give me a Guideline to download which dataset?

I'm going to use that dataset to proceed

**Comment by tianweiy** [comment]
good night, no problem. 

Here https://www.nuscenes.org/download Full Dataset, nuScenes Trainval

**Comment by wj-shin** [comment]
full data set have many part
So is any part okay?

**Comment by tianweiy** [comment]
yeah, mini / any part is ok. But you need full dataset to reproduce result. https://github.com/tianweiy/CenterPoint/issues/106#issuecomment-810310715 should fix the problem you faced

**Comment by wj-shin** [comment]
Thak you I will do your suggestion after 9hour 
And have a nice day!

**Comment by tianweiy** [comment]
tensorflow: no need for nuScenes. You need it for Waymo.

apex: for distributed training. single gpu no need

**Comment by wj-shin** [comment]
Thanks a lot!!!

**Comment by wj-shin** [comment]
So because I have only one gpu, I donn`t need to install apex.
is this right?

**Comment by tianweiy** [comment]
yes

**Comment by wj-shin** [comment]
must I create symlink?

**Comment by tianweiy** [comment]
the data location is assumed at that place, so you need either a symlink or hard link

**Comment by wj-shin** [comment]
can I use path like /data/sets/nuScenes???

I am poor at symlink, so I want use that way

**Comment by wj-shin** [comment]
and I just finish downloading dataset and extracting
so I just need Lidar data so can I delete some folder like  CAM_BACK

**Comment by tianweiy** [comment]
can I use path like /data/sets/nuScenes??? <- then remember to change path in the config 

 so I just need Lidar data so can I delete some folder like CAM_BACK < I believe so

**Comment by wj-shin** [comment]
samples_per_gpu=4
is it batch_size?

**Comment by tianweiy** [comment]
yes

**Comment by wj-shin** [comment]
I succeeded. I was able to succeed thanks to your help.
