### ISSUE TITLE
when train with volexnet in muilt GPU,I got this

### ISSUE THREAD

**Issue by Suodislie** [tianweiy/CenterPoint#120]
when i train with command "python -m torch.distributed.launch --nproc_per_node=4 ./tools/train.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn_flip.py "  . I got this error:
........
.........
2021-04-09 10:14:14,267 - INFO - finding looplift candidates
2021-04-09 10:14:15,525 - INFO - finding looplift candidates
2021-04-09 10:14:15,527 - INFO - finding looplift candidates
2021-04-09 10:14:17,066 - INFO - finding looplift candidates
2021-04-09 10:14:17,106 - INFO - finding looplift candidates
Traceback (most recent call last):
  File "tools/train.py", line 144, in <module>
    main()
  File "tools/train.py", line 139, in main
    logger=logger,
  File "/dahuafs/userdata/912333/CenterPoint-master/src1/det3d/torchie/apis/train.py", line 327, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/dahuafs/userdata/912333/CenterPoint-master/src1/det3d/torchie/trainer/trainer.py", line 543, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/dahuafs/userdata/912333/CenterPoint-master/src1/det3d/torchie/trainer/trainer.py", line 418, in train
    self.call_hook("after_train_iter")
  File "/dahuafs/userdata/912333/CenterPoint-master/src1/det3d/torchie/trainer/trainer.py", line 331, in call_hook
    getattr(hook, fn_name)(self)
  File "/dahuafs/userdata/912333/CenterPoint-master/src1/det3d/torchie/trainer/hooks/optimizer.py", line 18, in after_train_iter
    trainer.outputs["loss"].backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
     
     Someone suggest that i can modify 'tensor.view()' to 'tensor.continues().view()', but not'view()' in the code.  So also cannot Use .reshape(...) instead. 
     Looking forward to your reply

**Comment by tianweiy** [comment]
I never met this issue and it is a little hard to debug as the code ends at a backward pass... to my knowledge, reshape() is the same as contiguous().view()?  Does it work with single gpu ?

**Comment by Suodislie** [comment]
I tryed in single gpu,It print this error too. anyway ths for your reply.  I wonder if it will be related to the version

**Comment by tianweiy** [comment]
maybe, what is your pytorch version?

**Comment by Suodislie** [comment]
torch                  1.5.1
cuda                   10.1
python                3.6

**Comment by Suodislie** [comment]
torch 1.5.1
cuda 10.1
python 3.7

**Comment by tianweiy** [comment]
I tried 1.1 and 1.7. you can search for view in the code and see if replace some of them helps ...

**Comment by Suodislie** [comment]
I have searched before asking for your help，Now i will change all packages‘ version to yours，Thanks again！
