### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by hughlee815** [tianweiy/CenterPoint#128]
HI,

Thanks for the amazing centerpoint. but i encountered a problem when reproduce the model.
specifically, when i run
`python -m torch.distributed.launch --nproc_per_node=1 ./tools/train.py configs/waymo/pp/waymo_centerpoint_pp_two_cls_two_pfn_stride1_3x.py`
i got this error:
`WARNING:tensorflow:From /home/congcong.li/CenterPoint/det3d/datasets/waymo/waymo_common.py:17: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

Deformable Convolution not built!
2021-04-21 15:10:34,406 - INFO - Distributed training: False
2021-04-21 15:10:34,406 - INFO - torch.backends.cudnn.benchmark: False
2021-04-21 15:10:34,454 - INFO - Finish RPN Initialization
2021-04-21 15:10:34,455 - INFO - num_classes: [2]
Use HM Bias:  -2.19
2021-04-21 15:10:34,461 - INFO - Finish CenterHead Initialization
Using 1 sweeps
Using 2048 Frames
Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 132, in main
    logger=logger,
  File "/home/congcong.li/CenterPoint/det3d/torchie/apis/train.py", line 293, in train_detector
    model = model.cuda()
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
Traceback (most recent call last):
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/congcong.li/anaconda3/envs/centerpoint/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/congcong.li/anaconda3/envs/centerpoint/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/waymo/pp/waymo_centerpoint_pp_two_cls_two_pfn_stride1_3x.py']' returned non-zero exit status 1.`

i guess this may have something to do with the batchsize. but when i try to tune it, i couldn't see where it was set.

Thanks in advance.

**Comment by hughlee815** [comment]
samples_per_gpu is batch_size!
Problem solved!
Thanks so much!
