### ISSUE TITLE
Problems about val of waymo 

### ISSUE THREAD

**Issue by hughlee815** [tianweiy/CenterPoint#133]
i just can't generate the gt.bin by running
`python det3d/datasets/waymo/waymo_common.py --info_path data/Waymo/infos_val_01sweeps_filter_zero_gt.pkl --result_path data/Waymo/ --gt `
it throws an error:
2021-04-26 17:48:52.552840: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.0/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-04-26 17:48:52.552892: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
  0%|                                                                                                 | 0/1984 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "det3d/datasets/waymo/waymo_common.py", line 349, in <module>
    _create_gt_detection(infos, tracking=args.tracking)
  File "det3d/datasets/waymo/waymo_common.py", line 128, in _create_gt_detection
    annos = obj['objects']
KeyError: 'objects'

In addition, since I don't generate gt.bin successfully, so i treat detection_pred.bin as gt.bin. In theory, we should get all ones for mAP, but it turned to be all zeros, which is really very strange. 

Will you be so nice to also give some suggestions for these problems? 
Thanks in advance!

**Comment by hughlee815** [comment]
i guess the reason is my local code is different from the repo.

**Comment by WWW2323** [comment]
> i guess the reason is my local code is different from the repo.

hi, i also get this error when i generate gt.bin, how do you fix this problem?

**Comment by tianweiy** [comment]
pull the latest branch. Do you still see this problem? Also, you don't need gt.bin, you can submit to the server to get evaluation result (this is also faster than local evaluation
