### ISSUE TITLE
Problem occurs when using distributed training

### ISSUE THREAD

**Issue by Jay-9912** [tianweiy/CenterPoint#135]
Hi, tianweiy. I met a problem when I executed "python -m torch.distributed.launch --nproc_per_node=2 ./tools/train.py xxx/CenterPoint/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_dcn.py". I just downloaded a small subset of nuscenes dataset to test the code.  The programme got stuck for minutes, then error occurred:"

WARNING:tensorflow:From /home/wyue/jaywu/CenterPoint/det3d/datasets/waymo/waymo_common.py:17: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
WARNING:tensorflow:From /home/wyue/jaywu/CenterPoint/det3d/datasets/waymo/waymo_common.py:17: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

2021-04-27 17:15:05,142 - INFO - Distributed training: True
2021-04-27 17:15:05,142 - INFO - torch.backends.cudnn.benchmark: False
2021-04-27 17:15:05,242 - INFO - Finish RPN Initialization
2021-04-27 17:15:05,242 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
Use Deformable Convolution in the CenterHead!
Use HM Bias:  -2.19
Use Deformable Convolution in the CenterHead!
2021-04-27 17:15:05,300 - INFO - Finish CenterHead Initialization
2021-04-27 17:15:05,357 - INFO - {'car': 5, 'truck': 5, 'bus': 5, 'trailer': 5, 'construction_vehicle': 5, 'traffic_cone': 5, 'barrier': 5, 'motorcycle': 5, 'bicycle': 5, 'pedestrian': 5}
2021-04-27 17:15:05,357 - INFO - [-1]
2021-04-27 17:15:05,414 - INFO - load 2558 pedestrian database infos
2021-04-27 17:15:05,414 - INFO - load 3264 car database infos
2021-04-27 17:15:05,414 - INFO - load 773 traffic_cone database infos
2021-04-27 17:15:05,414 - INFO - load 129 bicycle database infos
2021-04-27 17:15:05,415 - INFO - load 1346 barrier database infos
2021-04-27 17:15:05,415 - INFO - load 366 truck database infos
2021-04-27 17:15:05,415 - INFO - load 245 bus database infos
2021-04-27 17:15:05,415 - INFO - load 174 construction_vehicle database infos
2021-04-27 17:15:05,415 - INFO - load 56 ignore database infos
2021-04-27 17:15:05,415 - INFO - load 162 motorcycle database infos
2021-04-27 17:15:05,415 - INFO - load 18 trailer database infos
10
2021-04-27 17:15:05,444 - INFO - After filter database:
2021-04-27 17:15:05,444 - INFO - load 2402 pedestrian database infos
2021-04-27 17:15:05,444 - INFO - load 2756 car database infos
2021-04-27 17:15:05,444 - INFO - load 639 traffic_cone database infos
2021-04-27 17:15:05,444 - INFO - load 122 bicycle database infos
2021-04-27 17:15:05,444 - INFO - load 1293 barrier database infos
2021-04-27 17:15:05,444 - INFO - load 334 truck database infos
2021-04-27 17:15:05,444 - INFO - load 226 bus database infos
2021-04-27 17:15:05,444 - INFO - load 161 construction_vehicle database infos
2021-04-27 17:15:05,444 - INFO - load 56 ignore database infos
2021-04-27 17:15:05,444 - INFO - load 133 motorcycle database infos
2021-04-27 17:15:05,444 - INFO - load 16 trailer database infos
10
Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 132, in main
    logger=logger,
  File "/home/wyue/jaywu/CenterPoint/det3d/torchie/apis/train.py", line 290, in train_detector
    find_unused_parameters=True,
  File "/home/wyue/anaconda3/envs/centerpoint_wu/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 286, in __init__
    self.broadcast_bucket_size)
  File "/home/wyue/anaconda3/envs/centerpoint_wu/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 410, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size, False)
RuntimeError: Socket Timeout

How can I fix it?

**Comment by tianweiy** [comment]
I have no clue. Please search online about this distributed training issue
