### ISSUE TITLE
Can not do inference using simple_inference_waymo.py

### ISSUE THREAD

**Issue by lfxx** [tianweiy/CenterPoint#139]
Fist of all,i want to know what does this scripts do?detecion or track.
and what checkpoint should i use?
Then when i download waymo test data,the data is below:
```
{'scene_name': '10504764403039842352_460_000_480_000', 'frame_name': '10504764403039842352_460_000_480_000_location_other_Dawn/Dusk_1558060923374527', 'frame_id': 0, 'lidars': {'points_xyz': array([[-37.286133  ,   3.137207  ,   3.7067337 ],
       [-37.28418   ,   3.2282715 ,   3.7067184 ],
       [-37.375     ,   3.3269043 ,   3.7104187 ],
       ...,
       [ -6.729186  ,   8.910209  ,  -0.27966785],
       [  0.15275276,  14.4378395 ,  -0.3565687 ],
       [ -0.6661949 ,   6.959557  ,  -0.15457088]], dtype=float32), 'points_feature': array([[0.25195312, 0.05269789],
       [0.37890625, 0.03513193],
       [0.33203125, 0.05269789],
       ...,
       [0.02099609, 0.63823   ],
       [0.05126953, 0.32204267],
       [0.01080322, 0.15809368]], dtype=float32)}}
```
get error below:
```
Traceback (most recent call last):
  File "tools/simple_inference_waymo_custom.py", line 154, in <module>
    detections = process_example(points, args.fp16)
  File "tools/simple_inference_waymo_custom.py", line 100, in process_example
    output = run_model(points, fp16)
  File "tools/simple_inference_waymo_custom.py", line 92, in run_model
    outputs = model(data_dict, return_loss=False)[0]
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/centerpoint/det3d/models/detectors/two_stage.py", line 156, in forward
    return_loss, **kwargs)
  File "/centerpoint/det3d/models/detectors/voxelnet.py", line 73, in forward_two_stage
    x, voxel_feature = self.extract_feat(data)
  File "/centerpoint/det3d/models/detectors/voxelnet.py", line 24, in extract_feat
    input_features = self.reader(data["features"], data["num_voxels"])
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/centerpoint/det3d/models/readers/voxel_encoder.py", line 20, in forward
    assert self.num_input_features == features.shape[-1]
AssertionError
```
My point only contain x,y,z,Where can i get data include 6 input features?quite confused.

**Comment by tianweiy** [comment]
detection. any single sweep Waymo checkpoint, you need to concatenate points_xyz  with points_feature

**Comment by tianweiy** [comment]
for benchmark inference, please use tools/dist_test.py

**Comment by YoushaaMurhij** [comment]
@tianweiy, I got this error when trying to use `simple_inference_waymo.py`. I am using the latest spconv version.
Did you met such an issue? Thanks!
```bash
x, voxel_feature = self.backbone(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/fmf/FMF/det3d/models/backbones/scn.py", line 156, in forward
    x = self.conv_input(ret)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/spconv/conv.py", line 196, in forward
    out_features = Fsp.indice_subm_conv(features, self.weight,
  File "/usr/local/lib/python3.8/dist-packages/spconv/functional.py", line 87, in forward
    return ops.indice_conv(features,
  File "/usr/local/lib/python3.8/dist-packages/spconv/ops.py", line 118, in indice_conv
    return torch.ops.spconv.indice_conv(features, filters, indice_pairs,
RuntimeError: expected scalar type Float but found Half
```

**Comment by tianweiy** [comment]
Both model and input need to be converted to fp16

**Comment by YoushaaMurhij** [comment]
I convert only voxels : `voxels = voxels.half()`. I think that is all, right?

**Comment by tianweiy** [comment]
No, also need model = model.half

**Comment by YoushaaMurhij** [comment]
Thanks. It worked!
