### ISSUE TITLE
Latency on waymo server

### ISSUE THREAD

**Issue by maiminh1996** [tianweiy/CenterPoint#173]
Hi tianweiy,

Thank you for sharing a nice work.
I recently used your code to submit on waymo server. Everything works well except the latency. Can you share a guide to get the latency? Specically, I got this error in case I used 2 sweeps in your code:

Traceback (most recent call last): File "/code/evaluator.py", line 117, in <module> latencies.append(process_example(timestamp_dir, out_dir)) File "/code/evaluator.py", line 71, in process_example output = wod_latency_submission.run_model(**data) File "/code/submission/lib/wod_latency_submission/__init__.py", line 155, in run_model data_dict = _process_inputs(kwargs) File "/code/submission/lib/wod_latency_submission/__init__.py", line 96, in _process_inputs lidar_range_image = input_sensor_dict[pre_field] # [64, 2650, 6] KeyError: 'TOP_RANGE_IMAGE_FIRST_RETURN_1'

Have you any suggestions?

Best regards,
Minh

**Comment by tianweiy** [comment]
Does this one work ? https://github.com/tianweiy/CenterPoint/pull/157#issuecomment-881522643

**Comment by maiminh1996** [comment]
Thanks a lot :D. I will try it and come back.

**Comment by tianweiy** [comment]
You may need some modifications (e.g. this one uses three frames)

**Comment by maiminh1996** [comment]
Yes, I got it. 
Besides, how do you set config on bucket cloud? I set as follows:
![Screenshot from 2021-08-13 09-24-32](https://user-images.githubusercontent.com/34424334/129320189-68a55c34-fa99-402a-9396-f0e45abfa3dc.png)
![Screenshot from 2021-08-13 09-24-15](https://user-images.githubusercontent.com/34424334/129320208-8e61a7c8-4a08-4f56-8124-ba2425778a2b.png)

Is it correct?
Thanks,

**Comment by tianweiy** [comment]
yes, that's right
