### ISSUE TITLE
How to solve the error ‘AT_CHECK’ was not declared?

### ISSUE THREAD

**Issue by rockywind** [tianweiy/CenterPoint#185]
When I run the script `bash setup.sh `
The error is 

> running build_ext
building 'deform_conv_cuda' extension
Emitting ninja build file /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o.d -pthread -B /home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/TH -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/include/python3.6m -c -c /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o 
c++ -MMD -MF /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o.d -pthread -B /home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/TH -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/include/python3.6m -c -c /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:69:31: error: ‘AT_CHECK’ was not declared in this scope
            weight.ndimension());
                               ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:194:73: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
                                                                         ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:301:76: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
                                                                            ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:417:73: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
                                                                         ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:497:70: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
                                                                      ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:579:70: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK(input.is_contiguous(), "input tensor has to be contiguous");
                                                                      ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ ^C
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ ls
build  build_bak  deform_conv.py  __init__.py  __pycache__  setup.py  src
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ rm -rf build
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ cp build_bak/ build
cp: omitting directory 'build_bak/'
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ cp -r build_bak/ build
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ ls
build  build_bak  deform_conv.py  __init__.py  __pycache__  setup.py  src
(CenterPoint_02) CN\zizhang.wu@shaxbw05:/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_ext
building 'deform_conv_cuda' extension
Emitting ninja build file /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ -MMD -MF /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o.d -pthread -B /home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/TH -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/include/python3.6m -c -c /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o 
c++ -MMD -MF /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o.d -pthread -B /home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/TH -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/CN/zizhang.wu/anaconda3/envs/CenterPoint_02/include/python3.6m -c -c /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp -o /newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:69:31: error: ‘AT_CHECK’ was not declared in this scope
            weight.ndimension());
                               ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_forward_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:194:73: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");
                                                                         ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_input_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:301:76: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), 3, "invalid batch size of offset");
                                                                            ^
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp: In function ‘int deform_conv_backward_parameters_cuda(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, float, int)’:
/newnfs/zzwu/08_3d_code/CenterPoint/det3d/ops/dcn/src/deform_conv_cuda.cpp:417:73: error: ‘AT_CHECK’ was not declared in this scope
   AT_CHECK((offset.size(0) == batchSize), "invalid batch size of offset");

**Comment by tianweiy** [comment]
see https://github.com/tianweiy/CenterPoint/issues/46
