### ISSUE TITLE
ROS inference file "multi_sweep_inference.py" bad callback: <function rslidar_callback at 0x7fdebadcf2f0> IndexError: invalid index to scalar variable

### ISSUE THREAD

**Issue by iamsiddhantsahu** [tianweiy/CenterPoint#19]
@muzi2045 Since the [Det3D](https://github.com/poodarchu/Det3D) code is written in Python3, I was able to configure ROS with Python3 using [this](https://medium.com/@beta_b0t/how-to-setup-ros-with-python-3-44a69ca36674) article.

After than created a catkin workspace and also created a catkin package "**centerpoint_ros_node**" with all the dependencies `catkin_create_pkg  centerpoint_ros_node std_msgs rospy sensor_msgs nav_msgs jsk_recognition_msgs` and copied the code of this repository and built the project with `catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so`.

Then I `source devel/setup.bash` and ran `rosrun centerpoint_ros_node multi_sweep_inference.py` and simultaneously ran the `rosbag play -l <nuScenes bag file name>.bag`. But I encountered the following error.

1. `rostopic echo /pp_boxes` does not output anything

```
get one frame lidar data.
 concate pointcloud shape: (173376, 5)
[ERROR] [1595837038.808509]: bad callback: <function rslidar_callback at 0x7fdebadcf2f0>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/siddhantsahu/centerpoint_p3_ws/src/centerpoint_ros_node/src/tools/multi_sweep_inference.py", line 339, in rslidar_callback
    scores, dt_box_lidar, types = proc_1.run()
  File "/home/siddhantsahu/centerpoint_p3_ws/src/centerpoint_ros_node/src/tools/multi_sweep_inference.py", line 192, in run
    outputs = self.net(self.inputs)[0]
  File "/home/siddhantsahu/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/detectors/point_pillars.py", line 48, in forward
    x = self.extract_feat(data)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/detectors/point_pillars.py", line 26, in extract_feat
    input_features, data["coors"], data["batch_size"], data["input_shape"]
  File "/home/siddhantsahu/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/readers/pillar_encoder.py", line 177, in forward
    self.nx = input_shape[0]
IndexError: invalid index to scalar variable.
```

**Comment by tianweiy** [comment]
@iamsiddhantsahu  at https://github.com/tianweiy/CenterPoint/blob/caa2f76ce7166e72b6c7ac7822917705ec282720/tools/multi_sweep_inference.py#L187

Change to shape = [grid_size]

**Comment by iamsiddhantsahu** [comment]
@tianweiy Yes, I have already tried that, but still getting this error
```
[ERROR] [1595862420.362335]: bad callback: <function rslidar_callback at 0x7f56679602f0>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/siddhantsahu/centerpoint_p3_ws/src/centerpoint_ros_node/src/tools/multi_sweep_inference.py", line 339, in rslidar_callback
    scores, dt_box_lidar, types = proc_1.run()
  File "/home/siddhantsahu/centerpoint_p3_ws/src/centerpoint_ros_node/src/tools/multi_sweep_inference.py", line 192, in run
    outputs = self.net(self.inputs)[0] #this is where the error is
  File "/home/siddhantsahu/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/detectors/point_pillars.py", line 52, in forward
    return self.bbox_head.loss(example, preds)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/bbox_heads/mg_head.py", line 1294, in loss
    hm_loss = self.crit(preds_dict['hm'], example['hm'][task_id])
KeyError: 'hm'
```

**Comment by tianweiy** [comment]
change https://github.com/tianweiy/CenterPoint/blob/caa2f76ce7166e72b6c7ac7822917705ec282720/tools/multi_sweep_inference.py#L192

to 

```
outputs = self.net(self.inputs, return_loss=False)[0] 
```

**Comment by iamsiddhantsahu** [comment]
Still
```
[ERROR] [1595862876.321550]: bad callback: <function rslidar_callback at 0x7f56497ac2f0>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/siddhantsahu/centerpoint_p3_ws/src/centerpoint_ros_node/src/tools/multi_sweep_inference.py", line 339, in rslidar_callback
    scores, dt_box_lidar, types = proc_1.run()
  File "/home/siddhantsahu/centerpoint_p3_ws/src/centerpoint_ros_node/src/tools/multi_sweep_inference.py", line 192, in run
    outputs = self.net(self.inputs, return_loss=False)[0] #this is where the error is
  File "/home/siddhantsahu/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/detectors/point_pillars.py", line 54, in forward
    return self.bbox_head.predict(example, preds, self.test_cfg)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/models/bbox_heads/mg_head.py", line 1459, in predict
    task_id=task_id
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/core/utils/center_utils.py", line 392, in ddd_decode
    keep = _circle_nms(boxes, min_radius=cfg.min_radius[task_id], post_max_size=cfg.post_max_size)
  File "/home/siddhantsahu/Desktop/CenterPoint/det3d/core/utils/center_utils.py", line 274, in _circle_nms
    keep = np.array(circle_nms(boxes.cpu().numpy(), thresh=min_radius))[:post_max_size]
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```

**Comment by tianweiy** [comment]
```
        with torch.no_grad():
            outputs = self.net(self.inputs, return_loss=False)[0]
```

just address the error message ..

**Comment by tianweiy** [comment]
Are there still any other errors?

**Comment by iamsiddhantsahu** [comment]
@tianweiy Thanks a lot! Yes, there are no errors now and the predictions also seems to match with the annotation ground truth. But there appears to be more number of unnecessary predicted boxes. 

The transparent boxes are ground truth and solid ones are predicted. I am using the centerpoint_pillar_512 trained model.

![Screenshot from 2020-07-27 21-08-57](https://user-images.githubusercontent.com/28495849/88562319-2a10ec00-d04e-11ea-80c1-795e43ff602e.png)

**Comment by tianweiy** [comment]
glad to hear. Pillar is our fastest / most inaccurate model so you can try other stronger model like https://github.com/tianweiy/CenterPoint/blob/master/configs/centerpoint/nusc_centerpoint_voxelnet_01voxel.py  You also want to tune this function to get desired number of output https://github.com/tianweiy/CenterPoint/blob/caa2f76ce7166e72b6c7ac7822917705ec282720/tools/multi_sweep_inference.py#L68

**Comment by iamsiddhantsahu** [comment]
Sure, will try with the best trained models. Fine tuning the `thresh` definitely helps. 
The model which I tried [nusc_centerpoint_pp_02voxel_circle_nms_demo](https://github.com/tianweiy/CenterPoint/blob/master/configs/centerpoint/nusc_centerpoint_pp_02voxel_circle_nms_demo.py) is it **only detection** or **detection + tracking** as well? Can I try to use the [centerpoint_voxel_1440_dcn_flip(Rotated NMS)](https://github.com/tianweiy/CenterPoint/blob/master/tracking_scripts/centerpoint_voxel_1440_dcn_flip_testset.sh) tracking model and other preas well?

**Comment by tianweiy** [comment]
only detection. Tracking script is [here](https://github.com/tianweiy/CenterPoint/tree/master/tools/tracking). You can use all pre-trained models but currently, the two ros scripts don't support the flip data augmentation.

**Comment by iamsiddhantsahu** [comment]
In addition to detection can **tracking** be visualized in ROS rivz as well?

**Comment by tianweiy** [comment]
not sure about rivz. Tracking is just detection + ID so I guess it is possible.

**Comment by muzi2045** [comment]
check the id info in output tensor and add it in visual box.

**Comment by YoushaaMurhij** [comment]
> check the id info in output tensor and add it in visual box.

The output tensor contains box3d_lidar, scores and label_preds. There is no id info.  Can you provide more information, please?

**Comment by tianweiy** [comment]
@YoushaaMurhij  Yeah, no id info. You need to follow the ```tools/tracking/pub_test.py``` to also generate id info in the ros inference file.

**Comment by xavidzo** [comment]
> @tianweiy Thanks a lot! Yes, there are no errors now and the predictions also seems to match with the annotation ground truth. But there appears to be more number of unnecessary predicted boxes.
> 
> The transparent boxes are ground truth and solid ones are predicted. I am using the centerpoint_pillar_512 trained model.
> 
> ![Screenshot from 2020-07-27 21-08-57](https://user-images.githubusercontent.com/28495849/88562319-2a10ec00-d04e-11ea-80c1-795e43ff602e.png)

HI @iamsiddhantsahu, one queston: I tried to reproduce the visualization of this screenshot in rviz, but only the predicted bounding boxes (i.e. only solid boxes) are shown, which come from the / pp_boxes topic. How did you manage to display also the ground truth boxes (transparent ones) at the same time? I didn't see any other topic from the rosbag file publishing this information.
I would appreciate your help, thanks.
