### ISSUE TITLE
How to run tracking with nuScenes.

### ISSUE THREAD

**Issue by LSQsjtu** [tianweiy/CenterPoint#191]
I run 
`python tools/nusc_tracking/pub_test.py --work_dir ./work_dirs --checkpoint ./work_dirs/centerpoint_voxel_1024/tracking_result.json` to validate set.
but I get error as follow.

```python
python tools/nusc_tracking/pub_test.py --work_dir ./work_dirs --checkpoint ./work_dirs/centerpoint_voxel_1024/tracking_result.json 
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 92.4 seconds.
======
Reverse indexing ...
Done reverse indexing in 25.3 seconds.
======
Deploy OK
Use hungarian: False
Begin Tracking

Traceback (most recent call last):
  File "tools/nusc_tracking/pub_test.py", line 191, in <module>
    main()
  File "tools/nusc_tracking/pub_test.py", line 113, in main
    outputs = tracker.step_centertrack(preds, time_lag)
  File "/data/CenterPoint/tools/nusc_tracking/pub_tracker.py", line 57, in step_centertrack
    if det['detection_name'] not in NUSCENES_TRACKING_NAMES:
KeyError: 'detection_name'
```
Is the checkpoint wrong? I downloaded frames_meta.json and tracking_result.json from [https://drive.google.com/drive/folders/19pdribrqU5JyGSmrrvIKQ_ecYIG1QW0t](url).
At your convenience, would you please tell me how to run tracking and explain the different files in [https://drive.google.com/drive/folders/19pdribrqU5JyGSmrrvIKQ_ecYIG1QW0t](url)?

**Comment by tianweiy** [comment]
Hi, thanks for the interest. 

> Is the checkpoint wrong? I downloaded frames_meta.json and tracking_result.json from

It is wrong. This checkpoint is the final tracking result (already have the tracking id, etc..). Additionally, the frames_meta.json is generated on the fly. 

Ideally, we want to do tracking given a **detection** files. They are available in this section https://github.com/tianweiy/CenterPoint/blob/master/configs/nusc/README.md#voxelnet

You can download the detection prediction from https://drive.google.com/drive/folders/1FOfCe9nWQrySUx42PlZyaKWAK2Or0sZQ
and pass it as arguments to --checkpoint in pub_test.py

Let me know if there are any further questions

**Comment by LSQsjtu** [comment]
I really appreciate your help very much！ It works now.

**Comment by LSQsjtu** [comment]
At your convenience, would you please tell me whether the messages in the detection prediction from [https://drive.google.com/drive/folders/1FOfCe9nWQrySUx42PlZyaKWAK2Or0sZQ](url) contain the feature of the points?
Dose the tracks in [https://github.com/tianweiy/CenterPoint/blob/master/tools/nusc_tracking/pub_tracker.py#L84](url) infer to the xy of the points in the first frame? why isn't it xyz? Thanks for your quick reply!

**Comment by tianweiy** [comment]
> does the file at the link contain the feature of the points?

What kind of features? I don't think we get any feature vector

> infer to the xy of the points in the first frame? why isn't it xyz?

We only infer speed for xy as z won't change assuming that th road is flat.

**Comment by LSQsjtu** [comment]
> We only infer speed for xy as z won't change assuming that the road is flat.

Thanks!

In the paper, it mentions "a 2D CNN architecture detection head finds object centers and regress to full 3D bounding boxes using center features". Does the detection files contain the feature of the centers?

**Comment by tianweiy** [comment]
It doesn't. This only contains the box parameters

**Comment by LSQsjtu** [comment]
Sorry to bother you again. I occur error when I Train & Evaluate.
Here is the error:
```python
python ./tools/dist_test.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py --work_dir work_dirs/centerpoint_voxel_1440 --checkpoint work_dirs/centerpoint_voxel_1440/epoch_20.pth --speed_test 
No APEX!
no apex
No Tensorflow
No APEX!
2021-09-09 02:27:58,802 - INFO - Distributed testing: False
2021-09-09 02:27:58,803 - INFO - torch.backends.cudnn.benchmark: False
2021-09-09 02:27:58,946 - INFO - Finish RPN Initialization
2021-09-09 02:27:58,947 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
2021-09-09 02:27:59,012 - INFO - Finish CenterHead Initialization
Use Val Set
10
2021-09-09 02:28:12,790 - INFO - work dir: work_dirs/centerpoint_voxel_1440
[                                                  ] 0/8837, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/dist_test.py", line 212, in <module>
    main()
  File "./tools/dist_test.py", line 168, in main
    model, data_batch, train_mode=False, local_rank=args.local_rank,
  File "/data/CenterPoint/det3d/torchie/apis/train.py", line 114, in batch_processor
    return model(example, return_loss=False)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/CenterPoint/det3d/models/detectors/voxelnet.py", line 46, in forward
    x, _ = self.extract_feat(example)
  File "/data/CenterPoint/det3d/models/detectors/voxelnet.py", line 37, in extract_feat
    data['voxels'], data["coors"], data["batch_size"], data["input_shape"]
KeyError: 'coors'
```
When I train, the same error occurs.
```python
2021-09-09 02:42:57,201 - INFO - Start running, host: root@19fd5e72c189, work_dir: /data/CenterPoint/work_dirs/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z
2021-09-09 02:42:57,201 - INFO - workflow: [('train', 1)], max: 20 epochs
2021-09-09 02:43:16,715 - INFO - finding looplift candidates
2021-09-09 02:43:16,916 - INFO - finding looplift candidates
2021-09-09 02:43:17,401 - INFO - finding looplift candidates
2021-09-09 02:43:17,781 - INFO - finding looplift candidates
2021-09-09 02:43:17,853 - INFO - finding looplift candidates
2021-09-09 02:43:17,888 - INFO - finding looplift candidates
Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 132, in main
    logger=logger,
  File "/data/CenterPoint/det3d/torchie/apis/train.py", line 327, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/data/CenterPoint/det3d/torchie/trainer/trainer.py", line 543, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/data/CenterPoint/det3d/torchie/trainer/trainer.py", line 410, in train
    self.model, data_batch, train_mode=True, **kwargs
  File "/data/CenterPoint/det3d/torchie/trainer/trainer.py", line 368, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/CenterPoint/det3d/models/detectors/voxelnet.py", line 46, in forward
    x, _ = self.extract_feat(example)
  File "/data/CenterPoint/det3d/models/detectors/voxelnet.py", line 37, in extract_feat
    data['voxels'], data["coors"], data["batch_size"], data["input_shape"]
KeyError: 'coors'
```
I create the data follow the instruction in [https://github.com/tianweiy/CenterPoint/blob/master/docs/NUSC.md#create-data](url). 
If possible,would you please tell me where the wrong is?

**Comment by tianweiy** [comment]
Hi, could you try to pull the latest code and try again? The lines in your log seem different from the latest one 

```
  File "/data/CenterPoint/det3d/models/detectors/voxelnet.py", line 46, in forward
    x, _ = self.extract_feat(example)
  File "/data/CenterPoint/det3d/models/detectors/voxelnet.py", line 37, in extract_feat
    data['voxels'], data["coors"], data["batch_size"], data["input_shape"]
```

**Comment by LSQsjtu** [comment]
I pulled the code from the branch new_release in the past. And now I pull the latest code from the default branch master.
But I occur another error.
```python
python ./tools/dist_test.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py --work_dir work_dirs/centerpoint_voxel_1440 --checkpoint work_dirs/centerpoint_voxel_1440/epoch_20.pth --speed_test --local_rank 3
No APEX!
no apex
No Tensorflow
No APEX!
2021-09-09 07:33:38,498 - INFO - Distributed testing: False
2021-09-09 07:33:38,498 - INFO - torch.backends.cudnn.benchmark: False
2021-09-09 07:33:38,619 - INFO - Finish RPN Initialization
2021-09-09 07:33:38,620 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
2021-09-09 07:33:38,663 - INFO - Finish CenterHead Initialization
Use Val Set
10
2021-09-09 07:33:43,173 - INFO - work dir: work_dirs/centerpoint_voxel_1440
Traceback (most recent call last):
  File "./tools/dist_test.py", line 211, in <module>
    main()
  File "./tools/dist_test.py", line 168, in main
    model, data_batch, train_mode=False, local_rank=args.local_rank,
  File "/data/CenterPointwithCost/det3d/torchie/apis/train.py", line 114, in batch_processor
    return model(example, return_loss=False)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/CenterPointwithCost/det3d/models/detectors/voxelnet.py", line 49, in forward
    x, _ = self.extract_feat(data)
  File "/data/CenterPointwithCost/det3d/models/detectors/voxelnet.py", line 26, in extract_feat
    input_features, data["coors"], data["batch_size"], data["input_shape"]
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/CenterPointwithCost/det3d/models/backbones/scn.py", line 156, in forward
    x = self.conv_input(ret)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/spconv/modules.py", line 123, in forward
    input = module(input)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/spconv/conv.py", line 155, in forward
    self.stride, self.padding, self.dilation, self.output_padding, self.subm, self.transposed, grid=input.grid)
  File "/root/miniconda3/envs/centerpoint/lib/python3.6/site-packages/spconv/ops.py", line 89, in get_indice_pairs
    stride, padding, dilation, out_padding, int(subm), int(transpose))
RuntimeError: /data/spconv/src/spconv/indice.cu 125
cuda execution failed with error 2
```

**Comment by LSQsjtu** [comment]
>But I occur another error.
I searched this problem. This is because of the memory. To test with one gpu and see the inference time, how much memory do I need?

**Comment by tianweiy** [comment]
> I pulled the code from the branch new_release in the past. And now I pull the latest code from the default branch master.
But I occur another error. 

Yeah, please use this branch

**Comment by tianweiy** [comment]
the memory depends on spconv and torch version. But in my current setup, torch 1.9 + cuda11.1 + spconv master, it is about 2GB (batch size 1).

**Comment by LSQsjtu** [comment]
Thanks for you quick reply!😁
