### ISSUE TITLE
Error during Cuda Extensions install: arch_list[-1] += '+PTX' IndexError: list index out of range

### ISSUE THREAD

**Issue by coolcatchagallcn** [tianweiy/CenterPoint#234]
I am using cuda 11.4 and found the following error?
Anyone ran into this too?

`(torch) user@AILAB-U-0029:/media/user/precp1/prob_centerpoint$ bash setup.sh
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.4'
running build_ext
building 'deform_conv_cuda' extension
Traceback (most recent call last):
  File "/media/user/precp1/prob_centerpoint/det3d/ops/dcn/setup.py", line 4, in <module>
    setup(
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 525, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.4'
running build_ext
building 'iou3d_nms_cuda' extension
Traceback (most recent call last):
  File "/media/user/precp1/prob_centerpoint/det3d/ops/iou3d_nms/setup.py", line 4, in <module>
    setup(
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 525, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/user/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
`

**Comment by tianweiy** [comment]
could you build the nms? The dcn is not used in current repo now (and you can ignore it).

You can change the setup.sh to the following

```
cd  det3d/ops/iou3d_nms
python setup.py build_ext --inplace

```

**Comment by coolcatchagallcn** [comment]
> could you build the nms? The dcn is not used in current repo now (and you can ignore it).
> 
> You can change the setup.sh to the following
> 
> ```
> cd  det3d/ops/iou3d_nms
> python setup.py build_ext --inplace
> ```

I found it's a torch version problem. The official torch website's conda install command leads to a cpu version. Install the pip one solved my problem. Thanks
