### ISSUE TITLE
Visualization on the validation set as in Demo.

### ISSUE THREAD

**Issue by YoushaaMurhij** [tianweiy/CenterPoint#24]
This error occurs when I try to run the demo visualization on the validation set. Do you know where is the problem ? 
I changes the directories to data/nuscenes and the directory to infos_val_10sweeps_withvelo_filter_True.pkl  and set the dataset to cfg.data.val.

```
(CenterPoint) ***********:~/CenterPoint_ws/CenterPoint$ python tools/demo.py 
Use HM Bias:  -2.19
10
Traceback (most recent call last):
  File "tools/demo.py", line 131, in <module>
    main()
  File "tools/demo.py", line 83, in main
    for i, data_batch in enumerate(data_loader):
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/*******/.conda/envs/CenterPoint/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

```

**Comment by tianweiy** [comment]
Can you give more details for this 

```
I changes the directories to data/nuscenes and the directory to infos_val_10sweeps_withvelo_filter_True.pkl and set the dataset to cfg.data.val
```

**Comment by tianweiy** [comment]
show git diff?

**Comment by YoushaaMurhij** [comment]
In demo.py:  I didn't change anything.

In _nusc_centerpoint_pp_02voxel_circle_nms_demo.py_:

```
#data_root = "demo/nuScenes"
data_root = "data/nuScenes"

#val_anno = "demo/nuScenes/demo_infos.pkl"
val_anno = "data/nuScenes/infos_val_10sweeps_withvelo_filter_True.pkl"
```

**Comment by tianweiy** [comment]
I will check this later. For now, to visualize on validation set, you can just use dist_test.py  and change this line to whatever number of images you want to see ```https://github.com/tianweiy/CenterPoint/blob/e14421df7b9fe86ae42b7349aeffed4705a9ab93/det3d/datasets/nuscenes/nusc_common.py#L658```

**Comment by YoushaaMurhij** [comment]
`torch.multiprocessing.set_sharing_strategy('file_system')
`solved the problem for me. I think this is because of the size of the validation set.
