### ISSUE TITLE
No module named 'torchie' 

### ISSUE THREAD

**Issue by TianhaoFu** [tianweiy/CenterPoint#240]
Hi, when i was using your codebase, i came across such error:
```
nuScenes devkit not Found!
No Tensorflow
nuScenes devkit not Found!
Deformable Convolution not built!
No Tensorflow
Traceback (most recent call last):
  File "./tools/train.py", line 168, in <module>
    main()
  File "./tools/train.py", line 72, in main
    cfg = Config.fromfile(args.config)
  File "/root/11/centerpoint/det3d/torchie/utils/config.py", line 95, in fromfile
    import torchie
ModuleNotFoundError: No module named 'torchie'
Deformable Convolution not built!
Traceback (most recent call last):
  File "./tools/train.py", line 168, in <module>
    main()
  File "./tools/train.py", line 72, in main
    cfg = Config.fromfile(args.config)
  File "/root/11/centerpoint/det3d/torchie/utils/config.py", line 95, in fromfile
    import torchie
ModuleNotFoundError: No module named 'torchie'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=1', 'voxelnet/infos_val_10sweeps_withvelo_filter_True.json']' returned non-zero exit status 1.
```
could you give me some ideas to fix it?
thanks!
:)

**Comment by tianweiy** [comment]
have you solved this ? I think you need to add centerpoint to your python path 

export PYTHONPATH="${PYTHONPATH}:/root/11/centerpoint/"

**Comment by TianhaoFu** [comment]
> have you solved this ? I think you need to add centerpoint to your python path
> 
> export PYTHONPATH="${PYTHONPATH}:/root/11/centerpoint/"

Hi, I solved it.
thanks!
