### ISSUE TITLE
iou3d cuda not built

### ISSUE THREAD

**Issue by yzhou377** [tianweiy/CenterPoint#270]
Hi Tianwei, 

Happy New Year! 

I am running into the following problem. I made a Dockerfile for easier transfer. However, I kept encountering 

```
iou3d cuda not built. You don't need this if you use circle_nms. Otherwise, refer to the advanced installation part to build this cuda extension
No Tensorflow
Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from det3d.models import build_detector
  File "/code/CenterPoint/det3d/models/__init__.py", line 29, in <module>
    from .roi_heads import * 
  File "/code/CenterPoint/det3d/models/roi_heads/__init__.py", line 1, in <module>
    from .roi_head_template import RoIHeadTemplate
  File "/code/CenterPoint/det3d/models/roi_heads/roi_head_template.py", line 12, in <module>
    from .target_assigner.proposal_target_layer import ProposalTargetLayer
  File "/code/CenterPoint/det3d/models/roi_heads/target_assigner/proposal_target_layer.py", line 11, in <module>
    from ....ops.iou3d_nms.iou3d_nms_utils import boxes_iou3d_gpu
  File "/code/CenterPoint/det3d/ops/iou3d_nms/__init__.py", line 1, in <module>
    from det3d.ops.iou3d_nms import iou3d_nms_cuda, iou3d_nms_utils
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
```

I am using nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04, python 3.6.2, spconv 1.0 (7342772), torch 1.1.0, torchvision 0.3.0. 

I checked that torch.cuda.is_available() is true and torch.version.cuda is correct. I tried to look for "ImportError: libtorch_cpu.so" but everyone is telling me it's a torch version issue. I followed your installation.md and I do not see any mismatch between my Dockerfile and your suggestion here. 

I have also attached the Dockerfile here. Hope you can help me on this! Thanks! 

[Dockerfile .md](https://github.com/tianweiy/CenterPoint/files/8001178/Dockerfile.md)

**Comment by tianweiy** [comment]
hi, not really sure. But this is the dockerfile i used in the path https://github.com/tianweiy/CenterPoint/blob/new_release/Dockerfile 

You may need to modify spconv / centerpoint path

**Comment by LXR1998-ran** [comment]
Hi, 

I met the same problem as you: `ImportError: libtorch.so: cannot open shared object file: No such file or directory`

May I ask that have you solved it yet? Thanks for your help.

**Comment by yzhou377** [comment]
Hi LXR,

The issue seems to be a NVIDIA driver - CUDA - torch - torchvision mismatch problem on our side. Here is a working dockerfile on our end with NVIDIA 441 driver.

```
# modified from https://github.com/xfbs/docker-openpcdet
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04
# This is an image from the dockerhub published by the offical nvidiagitlab account. 
# It contains cuda 10.0 cudnn7, and ubuntu 16.04
RUN apt-get update 
RUN apt-get install -y software-properties-common 
RUN add-apt-repository ppa:fkrull/deadsnakes
RUN apt-get update
RUN apt-get install -y python3.6-dev python3-pip apt-transport-https ca-certificates gnupg software-properties-common wget git ninja-build libboost-dev build-essential


RUN python3.6 -m pip install --upgrade "pip < 21.0" 
RUN python3.6 -m pip install torch==1.7.1 torchvision==0.8.2

# Install CMake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - > /etc/apt/trusted.gpg.d/kitware.gpg
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
RUN apt-get update && apt install -y cmake

# Install spconv
WORKDIR /code
RUN git clone -b v1.2.1 https://github.com/traveller59/spconv.git --recursive 
WORKDIR /code/spconv
ENV SPCONV_FORCE_BUILD_CUDA=1
RUN python3.6 setup.py bdist_wheel
RUN python3.6 -m pip install dist/*.whl

# Install LLVM 10
WORKDIR /code
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 10
# OpenPCDet dependencies fail to install unless LLVM 10 exists on the system
# and there is a llvm-config binary available, so we have to symlink it here.
RUN ln -s /usr/bin/llvm-config-10 /usr/bin/llvm-config

# Install APEX
WORKDIR /code
RUN git clone --branch centerNet_mod https://github.com/yzhou377/apex.git
WORKDIR /code/apex
RUN python3.6 -m pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

ARG TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5+PTX"

# Install CenterPoint
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 0
COPY ./requirements.txt /code/requirements_install.txt
RUN python3.6 -m pip install -r /code/requirements_install.txt
RUN python3.6 -m pip uninstall opencv-python  --yes
RUN python3.6 -m pip install opencv-python-headless 
RUN rm /code/requirements_install.txt

RUN python3.6 -m pip install waymo-open-dataset-tf-1-15-0==1.2.0 

RUN chmod -R +777 /code 

ENV PYTHONPATH "${PYTHONPATH}:/code/CenterPoint"
WORKDIR /code/CenterPoint
```
