### ISSUE TITLE
Found No Driver Error

### ISSUE THREAD

**Issue by LXR1998-ran** [tianweiy/CenterPoint#287]
Hi Tianwei,

I used python3.6 + torch1.8.2 + cuda10.2 to run centerpoint using `examples/point_pillars/configs/nusc_all_pp_centernet_tracking.py`, but run into error

```

Traceback (most recent call last):
File "./tools/train.py", line 141, in <module>
main()
File "./tools/train.py", line 136, in main
logger=logger,
File "/home/xrli/repos/CenterPoint/det3d/torchie/apis/train.py", line 299, in train_detector
model = model.cuda()
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in cuda
return self._apply(lambda t: t.cuda(device))
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
module._apply(fn)
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
module._apply(fn)
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 387, in _apply
module._apply(fn)
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 409, in _apply
param_applied = fn(param)
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in <lambda>
return self._apply(lambda t: t.cuda(device))
File "/home/xrli/libs/miniconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```

However, my driver was well installed and the `torch.cuda.is_available()` is TRUE and could successfully run other projects.

Could you help me with that, is there something wrong with cuda version? 

Thanks very much for your help.

**Comment by LXR1998-ran** [comment]
Problem solved:)
