### ISSUE TITLE
How can I visualize the result of the test set?

### ISSUE THREAD

**Issue by 18lalala** [tianweiy/CenterPoint#289]
Is there a visualization tool?

**Comment by tianweiy** [comment]
there is no file that works out of the box. But you can check this file to get an idea for how to use open3d to visualize detections https://github.com/tianweiy/CenterPoint/blob/master/tools/visual.py

**Comment by 18lalala** [comment]
> there is no file that works out of the box. But you can check this file to get an idea for how to use open3d to visualize detections https://github.com/tianweiy/CenterPoint/blob/master/tools/visual.py

thx.btw, when the model predicts the velocity,the out_channel of head change from 7 to 9, what is the other output except velocity?

**Comment by tianweiy** [comment]
you can see the mapping here https://github.com/tianweiy/CenterPoint/blob/3c64610e78756990c8f67732749806a7a83caa5a/det3d/datasets/waymo/waymo_common.py#L71

**Comment by 18lalala** [comment]
sorry to disturb you tianwei, I am trying single_infernece_ros.py in your code, and when processing the point cloud data,I meet this error:
[ERROR] [1648210357.932211]: bad callback: <function rslidar_callback at 0x7fa72e739e18>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "./tools/single_infernece_ros.py", line 202, in rslidar_callback
    scores, dt_box_lidar, types = proc_1.run(np_p)
  File "./tools/single_infernece_ros.py", line 112, in run
    voxels, coords, num_points = self.voxel_generator.generate(self.points)
  File "/home/puzek/ljy_projects/CenterPoint/det3d/core/input/voxel_generator.py", line 29, in generate
    max_voxels,
  File "/home/puzek/ljy_projects/CenterPoint/det3d/ops/point_cloud/point_cloud_ops.py", line 149, in points_to_voxel
    num_points_per_voxel = np.zeros(shape=(max_voxels,), dtype=np.int32)
TypeError: 'list' object cannot be interpreted as an integer

there is my publish demo:
`import rospy
from std_msgs.msg import String
import scipy.io as scio
from sensor_msgs.msg import PointCloud2
from sensor_msgs.msg import PointField
import numpy as np
import time
from std_msgs.msg import Header
from sensor_msgs import point_cloud2

import numpy as np
 
from sensor_msgs.msg import PointField
from sensor_msgs.msg import PointCloud2
 
def talker():
    pub = rospy.Publisher('lidar_top', PointCloud2, queue_size=1)
    rospy.init_node('node', anonymous=True)
    rate = rospy.Rate(10)


    while not rospy.is_shutdown():
        path = './data/nuScenes/v1.0-test/samples/LIDAR_TOP/n008-2018-08-01-15-34-25-0400__LIDAR_TOP__1533152214547215.pcd.bin'

        bin_pcd = np.fromfile(path, dtype=np.float32)
        pointstest = bin_pcd.reshape((-1, 5))[:, 0:5]
        cloud_arr = np.asarray(pointstest, np.float32)
        print(cloud_arr.shape)

        points = np.zeros_like(cloud_arr)
        points[:, 0] = cloud_arr[:, 2]
        points[:, 1] = cloud_arr[:, 0]
        points[:, 2] = cloud_arr[:, 1]
        points[:, 3] = cloud_arr[:, 3]
        points[:, 4] = cloud_arr[:, 4]
        msg = PointCloud2()
        msg.header.stamp = rospy.Time().now()
        msg.header.frame_id = "Velodyne"

        if len(points.shape) == 3:
            msg.height = points.shape[1]
            msg.width = points.shape[0]
        else:
            msg.height = 1
            msg.width = len(points)

        msg.fields = [
            PointField('x', 0, PointField.FLOAT32, 1),
            PointField('y', 4, PointField.FLOAT32, 1),
            PointField('z', 8, PointField.FLOAT32, 1),
            PointField('r', 12, PointField.FLOAT32, 1),
            PointField('t', 16, PointField.FLOAT32, 1)]
        msg.is_bigendian = False
        msg.point_step = 20
        msg.row_step = msg.point_step * points.shape[0]
        msg.is_dense = False
        msg.data = np.asarray(points, np.float32).tostring()

        pub.publish(msg)
        print('send!')
        rate.sleep()
        
if __name__ == '__main__':     

    talker()
    rospy.spin()
`

**Comment by 18lalala** [comment]
I solved this by changing the max_voxel_num in the config file from a list to a integer.
The model trained on nuscenes dataset doesn't work well for my data collected by 16 thread lidar,I am doubting which hyperparameter will be useful to enhance the performance?

**Comment by tianweiy** [comment]
there are a few reasons. 

All nuscenes model uses ten sweep for training so it may internally rely heavily on the motion cues for detection, making them worse for detecting based on single frame input. 

Nuscenes lidar may be quite different from yours. 

You could probably try model trained on Waymo with this file https://github.com/tianweiy/CenterPoint/blob/master/tools/simple_inference_waymo.py (may need some tiny syntax fix to work with current repo)

**Comment by 18lalala** [comment]
Thanks, I will try it, did you provide pretrained models on Waymo?

**Comment by 18lalala** [comment]
btw,my test data is a continuous ploud cloud data stream record by 16 line Velodyne lidar in 10 mins,is this satisfy the "motion cues"?

**Comment by tianweiy** [comment]
> Thanks, I will try it, did you provide pretrained models on Waymo?

send me an email (I can't publish it due to Waymo license)

> btw,my test data is a continuous ploud cloud data stream record by 16 line Velodyne lidar in 10 mins,is this satisfy the "motion cues"?

it depends on how you use the data. You need to do multiple sweep aggregation (transform lidar to current frame) to form the ten sweep inputs. The frequency may also need to match exactly to work well  https://github.com/tianweiy/CenterPoint/issues/291

Maybe you should first try Waymo single frame model and  see

**Comment by 18lalala** [comment]
I will try Waymo first
I noticed [multi_sweep_inference_ros.py](https://github.com/tianweiy/CenterPoint/blob/master/tools/multi_sweep_inference_ros.py) subscribe odom topic, what does it refer to?

**Comment by tianweiy** [comment]
i don't know (if you check git history this file is authored by some other people and I don't know anything about ros lol

**Comment by Liaoqing-up** [comment]
> there is no file that works out of the box. But you can check this file to get an idea for how to use open3d to visualize detections https://github.com/tianweiy/CenterPoint/blob/master/tools/visual.py

hello, tianweiy, how can i generate the file that should be passed to visual.py, the file seems include points and detections, is these any script in this project i can use?
