### ISSUE TITLE
    from . import iou3d_nms_cuda error

### ISSUE THREAD

**Issue by zzm-hl** [tianweiy/CenterPoint#311]
`(centerpoint) zzm@zzm:/media/zzm/data/code/CenterPoint$ python ./tools/train.py /media/zzm/data/code/CenterPoint/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py 
iou3d cuda not built. You don't need this if you use circle_nms. Otherwise, refer to the advanced installation part to build this cuda extension
no apex
No Tensorflow
Deformable Convolution not built!
Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from det3d.models import build_detector
  File "/media/zzm/data/code/CenterPoint/tools/det3d/models/__init__.py", line 29, in <module>
    from .roi_heads import * 
  File "/media/zzm/data/code/CenterPoint/tools/det3d/models/roi_heads/__init__.py", line 1, in <module>
    from .roi_head_template import RoIHeadTemplate
  File "/media/zzm/data/code/CenterPoint/tools/det3d/models/roi_heads/roi_head_template.py", line 12, in <module>
    from .target_assigner.proposal_target_layer import ProposalTargetLayer
  File "/media/zzm/data/code/CenterPoint/tools/det3d/models/roi_heads/target_assigner/proposal_target_layer.py", line 11, in <module>
    from ....ops.iou3d_nms.iou3d_nms_utils import boxes_iou3d_gpu
  File "/media/zzm/data/code/CenterPoint/tools/det3d/ops/iou3d_nms/__init__.py", line 1, in <module>
    from det3d.ops.iou3d_nms import iou3d_nms_cuda, iou3d_nms_utils
  File "/media/zzm/data/code/CenterPoint/tools/det3d/ops/iou3d_nms/iou3d_nms_utils.py", line 8, in <module>
    from . import iou3d_nms_cuda
ImportError: cannot import name 'iou3d_nms_cuda'`
How can I solve the error ? thanks!

**Comment by zzm-hl** [comment]
before it ,I have run the bash setup.sh　
`(centerpoint) zzm@zzm:/media/zzm/data/code/CenterPoint$ bash setup.sh 
running build_ext
building 'deform_conv_cuda' extension
Emitting ninja build file /media/zzm/data/code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/zzm/anaconda3/envs/centerpoint/compiler_compat -L/home/zzm/anaconda3/envs/centerpoint/lib -Wl,-rpath=/home/zzm/anaconda3/envs/centerpoint/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/zzm/data/code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda.o /media/zzm/data/code/CenterPoint/det3d/ops/dcn/build/temp.linux-x86_64-3.6/src/deform_conv_cuda_kernel.o -L/home/zzm/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.6/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so -> 
running build_ext
building 'iou3d_nms_cuda' extension
Emitting ninja build file /media/zzm/data/code/CenterPoint/det3d/ops/iou3d_nms/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /home/zzm/anaconda3/envs/centerpoint/compiler_compat -L/home/zzm/anaconda3/envs/centerpoint/lib -Wl,-rpath=/home/zzm/anaconda3/envs/centerpoint/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/zzm/data/code/CenterPoint/det3d/ops/iou3d_nms/build/temp.linux-x86_64-3.6/src/iou3d_cpu.o /media/zzm/data/code/CenterPoint/det3d/ops/iou3d_nms/build/temp.linux-x86_64-3.6/src/iou3d_nms_api.o /media/zzm/data/code/CenterPoint/det3d/ops/iou3d_nms/build/temp.linux-x86_64-3.6/src/iou3d_nms.o /media/zzm/data/code/CenterPoint/det3d/ops/iou3d_nms/build/temp.linux-x86_64-3.6/src/iou3d_nms_kernel.o -L/home/zzm/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda-11.1/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.6/iou3d_nms_cuda.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/iou3d_nms_cuda.cpython-36m-x86_64-linux-gnu.so -> 
`

**Comment by zzm-hl** [comment]
I have solve the problem by restart，thank  you
