### ISSUE TITLE
When I try to use pub_test to track, The following problem occurs

### ISSUE THREAD

**Issue by qfwysw** [tianweiy/CenterPoint#325]
Traceback (most recent call last):
  File "/opt/data/private/glchen/projects/vedio_petr/vedio_petr_baseline/tools/nusc_tracking/pub_test.py", line 194, in <module>
    eval_tracking()
  File "/opt/data/private/glchen/projects/vedio_petr/vedio_petr_baseline/tools/nusc_tracking/pub_test.py", line 159, in eval_tracking
    eval(os.path.join(args.work_dir, 'tracking_result.json'),
  File "/opt/data/private/glchen/projects/vedio_petr/vedio_petr_baseline/tools/nusc_tracking/pub_test.py", line 180, in eval
    metrics_summary = nusc_eval.main()
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/evaluate.py", line 205, in main
    metrics, metric_data_list = self.evaluate()
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/evaluate.py", line 135, in evaluate
    accumulate_class(class_name)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/evaluate.py", line 131, in accumulate_class
    curr_md = curr_ev.accumulate()
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/algo.py", line 118, in accumulate
    thresholds, recalls = self.compute_thresholds(gt_box_count)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/algo.py", line 298, in compute_thresholds
    _, scores = self.accumulate_threshold(threshold=None)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/algo.py", line 268, in accumulate_threshold
    events = acc.events.loc[frame_id]
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/mot.py", line 64, in events
    self.cached_events_df = MOTAccumulatorCustom.new_event_dataframe_with_data(self._indices, self._events)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/nuscenes/eval/tracking/mot.py", line 39, in new_event_dataframe_with_data
    idx = pd.MultiIndex.from_tuples(indices, names=['FrameId', 'Event'])
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 204, in new_meth
    return meth(self_or_cls, *args, **kwargs)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 566, in from_tuples
    return cls.from_arrays(arrays, sortorder=sortorder, names=names)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 493, in from_arrays
    return cls(
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 335, in __new__
    result._set_names(names)
  File "/opt/conda/envs/vpb1/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 1436, in _set_names
    raise ValueError(
ValueError: Length of names must match number of levels in MultiIndex.

Process finished with exit code 1

**Comment by tianweiy** [comment]
may relate to https://github.com/tianweiy/CenterPoint/issues/292#issuecomment-1105121604

I don't think it has anything to do with my repo. Probably try a few pandas / numpy versions ...

**Comment by qfwysw** [comment]
Thanks for your replay. The error is caused from the version of the motmetrics. The version of the motmetrics should <=1.1.3.
