### ISSUE TITLE
nuScenes data val OSError: latest.pth is not a checkpoint file

### ISSUE THREAD

**Issue by 751565516** [tianweiy/CenterPoint#330]
Hi,first, thank you for your outstanding work.
When I finish training, 
and then ` python ./tools/dist_test.py /home/zj/CenterPoint/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py --work_dir work_dirs/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py --checkpoint work_dirs/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py/latest.pth --speed_test`
The following error occurred during the test

(cp) zj@zj-Legion-Y7000-2019-PG0:~/CenterPoint$ python ./tools/dist_test.py /home/zj/CenterPoint/configs/nusc/pp/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py --work_dir work_dirs/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py --checkpoint work_dirs/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py/latest.pth --speed_test 
No Tensorflow
Deformable Convolution not built!
2022-06-22 10:38:42,421 - INFO - Distributed testing: False
2022-06-22 10:38:42,421 - INFO - torch.backends.cudnn.benchmark: False
2022-06-22 10:38:42,467 - INFO - Finish RPN Initialization
2022-06-22 10:38:42,468 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
2022-06-22 10:38:42,572 - INFO - Finish CenterHead Initialization
Use Val Set
10
Traceback (most recent call last):
  File "./tools/dist_test.py", line 211, in <module>
    main()
  File "./tools/dist_test.py", line 123, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/home/zj/CenterPoint/det3d/torchie/trainer/checkpoint.py", line 200, in load_checkpoint
    raise IOError("{} is not a checkpoint file".format(filename))
OSError: work_dirs/nusc_centerpoint_pp_02voxel_two_pfn_10sweep.py/latest.pth is not a checkpoint file
![图片](https://user-images.githubusercontent.com/68498595/174944123-7529a49e-b457-4417-85cd-9bc9f5b99662.png)

Later, I used the model centerpoint_ pillar provided by MODEL Zoo, still get this error.
![图片](https://user-images.githubusercontent.com/68498595/174944210-a9c0f675-9a0f-4499-a52a-f950772909c0.png)

So,What can I do to solve this problem？

**Comment by tianweiy** [comment]
The path for checkpoint is wrong. You should not have .py in the path

**Comment by 751565516** [comment]
sorry,I made a low-level mistake.

In addition, I'd like to ask how to carry out detection visualization and tracking visualization?

Thank you very much!
