### ISSUE TITLE
/usr/bin/ld: cannot find /usr/local/cudnn/lib64: file format not recognized

### ISSUE THREAD

**Issue by hygxy** [tianweiy/CenterPoint#337]
when running "python setup.py bdist_wheel". i get the following error, please help!
```bash
running bdist_wheel
running build
running build_py
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/yh/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/yh/Desktop/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- Caffe2: CUDA detected: 11.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.2/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.2
-- Caffe2: Header version is: 11.2
-- Found cuDNN: v8.2.1  (include: /usr/local/cudnn/include, library: /usr/local/cudnn/lib64)
-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
-- pybind11 v2.10.0 dev1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yh/Desktop/spconv/build/temp.linux-x86_64-3.6
[ 15%] Built target spconv_nms
[ 23%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv.so
[ 38%] Built target spconv_utils
/usr/bin/ld: cannot find /usr/local/cudnn/lib64: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:241: ../lib.linux-x86_64-3.6/spconv/libspconv.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: src/spconv/CMakeFiles/spconv.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 73, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/yh/anaconda3/envs/centerpoint/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

```

**Comment by Adam1904** [comment]
I have the same problem
