### ISSUE TITLE
No such file or directory: '/newo_search/data/nuScenes/samples/LIDAR_TOP/n015-2018-07-18-11-50-34+0800__LIDAR_TOP__1531886030950126.pcd.bin'

### ISSUE THREAD

**Issue by Tom-zgt** [tianweiy/CenterPoint#360]
Traceback (most recent call last):
  File "./tools/train.py", line 168, in <module>
    main()
  File "./tools/train.py", line 163, in main
    logger=logger,
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/torchie/apis/train.py", line 326, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/torchie/trainer/trainer.py", line 542, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/torchie/trainer/trainer.py", line 394, in train
    for i, data_batch in enumerate(data_loader):
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/workspace/zhengguangting/.conda/envs/centerpoint/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 190, in __getitem__
    return self.get_sensor_data(idx)
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 185, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/datasets/pipelines/compose.py", line 25, in __call__
    res, info = t(res, info)
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/datasets/pipelines/loading.py", line 126, in __call__
    points = read_file(str(lidar_path), virtual=res["virtual"])
  File "/data/workspace/zhengguangting/others_work/CenterPoint/det3d/datasets/pipelines/loading.py", line 40, in read_file
    points = np.fromfile(path, dtype=np.float32).reshape(-1, 5)[:, :num_point_feature]
FileNotFoundError: [Errno 2] No such file or directory: '/newo_search/data/nuScenes/samples/LIDAR_TOP/n015-2018-07-18-11-50-34+0800__LIDAR_TOP__1531886030950126.pcd.bin'

**Comment by Byte247** [comment]
Did you solve it? I run into it when I try to evaluate

**Comment by Byte247** [comment]
I get a very similar one: FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/ws/data/nuScenes/samples/LIDAR_TOP/n008-2018-09-18-14-35-12-0400__LIDAR_TOP__1537296082950475.pcd.bin'

**Comment by ZXueYu** [comment]
Did anyone solve this problem? The dataset in the last error path is nuScenes. 
When my file name is nuscenes, I get an issue like this.
![1](https://github.com/tianweiy/CenterPoint/assets/87346093/f505495d-79c9-4970-abd3-20610b7b5009)
![2](https://github.com/tianweiy/CenterPoint/assets/87346093/a3abb6da-e5d3-405c-a6eb-2c3a4dfa68b2)
Then I change the dataset to nuScenes, another question arises.
![3](https://github.com/tianweiy/CenterPoint/assets/87346093/1a1e38b4-3cba-4c47-a938-691d43dc44a4)
![4](https://github.com/tianweiy/CenterPoint/assets/87346093/1dd5767d-254b-4d7e-bf77-b2b9c7337f2c)

**Comment by safetylab24** [comment]
Hey, did you solve it? I am running into a similar issue. Here's the exact error: 
FileNotFoundError: [Errno 2] No such file or directory: /home/media/datasets/nuscenes/sweeps/LIDAR_TOP/n015-2018-07-18-11-07-57+0800__LIDAR_TOP__1531883530649557.pcd.bin

**Comment by safetylab24** [comment]
The issue is just that the LIDAR blobs weren't being downloaded. 
![image](https://github.com/user-attachments/assets/aa25ca12-8036-4250-9a8e-b6fefa8573a1)
Make sure to download all the files, not just the keyframes.

**Comment by CGL-learner** [comment]
![Image](https://github.com/user-attachments/assets/f4114065-499e-4334-a18d-9917685be73f)

I download these files, then meet the problem FileNotFoundError: file "./data/nuscenes/samples/LIDAR_TOP/n015-2018-07-18-11-07-57+0800__LIDAR_TOP__1531883530449377.pcd.bin" does not exist.
I meet the same problem, how do you solve this problem??
