### ISSUE TITLE
There is a error when run tracking on waymo dataset. 

### ISSUE THREAD

**Issue by sjtuljw520** [tianweiy/CenterPoint#364]
When I run the following to do the tracking:
`python tools/waymo_tracking/test.py --work_dir work_dirs/waymo_centerpoint_voxelnet_3x --checkpoint work_dirs/waymo_centerpoint_voxelnet_3x/prediction.pkl --info_path data/Waymo/infos_val_01sweeps_filter_zero_gt.pk`

get error like this:
Traceback (most recent call last):
  File "tools/waymo_tracking/test.py", line 263, in <module>
    main()
  File "tools/waymo_tracking/test.py", line 92, in main
    global_preds, detection_results = convert_detection_to_global_box(predictions, infos)
  File "tools/waymo_tracking/test.py", line 233, in convert_detection_to_global_box
    box3d = transform_box(box3d, pose)
  File "tools/waymo_tracking/test.py", line 176, in transform_box
    velocity = box[..., [6, 7]] 
IndexError: index 7 is out of bounds for axis 1 with size 7

**Comment by tianweiy** [comment]
Hi, for centerpoint you will need to use a config with velocity prediction e.g. https://github.com/tianweiy/CenterPoint/blob/master/configs/waymo/voxelnet/two_stage/waymo_centerpoint_voxelnet_two_sweep_two_stage_bev_5point_ft_6epoch_freeze_with_vel.py 

Otherwise, you can refer to different tracking methods based solely on detection results, e.g. https://github.com/tusen-ai/SimpleTrack

**Comment by sjtuljw520** [comment]
OK，thank you for kind help. @tianweiy
