### ISSUE TITLE
problem on the pub_test.py

### ISSUE THREAD

**Issue by JimmyGea** [tianweiy/CenterPoint#368]
Hi,thank you for your great work.
l try to follow your work on Getting Started with CenterPoint on nuScenes,when l running this command: python tools/nusc_tracking/pub_test.py --work_dir work_dirs/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z/output/outputs  --checkpoint work_dirs/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z/output/infos_val_10sweeps_withvelo_filter_True.json
The following error occurred during the pub_test.

Traceback (most recent call last):
  File "tools/nusc_tracking/pub_test.py", line 194, in <module>
    eval_tracking()
  File "tools/nusc_tracking/pub_test.py", line 161, in eval_tracking
    args.root
  File "tools/nusc_tracking/pub_test.py", line 179, in eval
    metrics_summary = nus_eval.main()
  File "/home/xuejunming/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py", line 205, in main
    metrics, metric_data_list = self.evaluate()
  File "/home/xuejunming/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py", line 135, in evaluate
    accumulate_class(class_name)
  File "/home/xuejunming/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py", line 131, in accumulate_class
    curr_md = curr_ev.accumulate()
  File "/home/xuejunming/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/algo.py", line 156, in accumulate
    assert unachieved_thresholds + duplicate_thresholds + len(thresh_metrics) == self.num_thresholds
AssertionError

![error](https://user-images.githubusercontent.com/119722941/205428272-976b1130-d2b3-466a-853d-ca9f0d56f973.png)

Thanks for your kind attention and look forward your prompt reply.

**Comment by JimmyGea** [comment]
If I may ask one more question, how to create infos_train_10sweeps_withvelo_filter_True.json?  I can only create infos_val_10sweeps_withvelo_filter_True.json according to your instructions.

**Comment by tianweiy** [comment]
to generate detection on training set, modify val anno path to info_train https://github.com/tianweiy/CenterPoint/blob/d3a248fa56db2601860d576d5934d00fee9916eb/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_flip.py#L171

**Comment by tianweiy** [comment]
you can also directly use prediction from https://github.com/tianweiy/CenterPoint/issues/249
