### ISSUE TITLE
Why such a problem when I run that python tools/nusc_tracking/pub_test.py --work_dir work_dirs --checkpoint work_dirs/infos_val_10sweeps_withvelo_filter_True.json

### ISSUE THREAD

**Issue by ZhangTingyang** [tianweiy/CenterPoint#389]
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 29.8 seconds.
======
Reverse indexing ...
Done reverse indexing in 11.3 seconds.
======
Deploy OK
Use hungarian: False
Traceback (most recent call last):
  File "tools/nusc_tracking/pub_test.py", line 190, in <module>
    main()
  File "tools/nusc_tracking/pub_test.py", line 84, in main
    predictions=json.load(f)['results']
KeyError: 'results'

**Comment by ZXueYu** [comment]
When I was tracking, I encountered the same problem. How did you solve it?
