### ISSUE TITLE
KeyError: '1b9a789e08bb4b7b89eacb2176c70840'

### ISSUE THREAD

**Issue by ZhangTingyang** [tianweiy/CenterPoint#390]
root@autodl-container-a2b111a626-eef41984:~/autodl-tmp/CenterPoint# python tools/nusc_tracking/pub_test.py --work_dir model  --checkpoint work_dirs/result/infos_val_10sweeps_withvelo_filter_True.json  --version v1.0-test  --root data/nuScenes/v1.0-test    

======
Loading NuScenes tables for version v1.0-test...
23 category,
8 attribute,
4 visibility,
0 instance,
12 sensor,
1800 calibrated_sensor,
462901 ego_pose,
15 log,
150 scene,
6008 sample,
462901 sample_data,
0 sample_annotation,
4 map,
Done loading in 3.7 seconds.
======
Reverse indexing ...
Done reverse indexing in 1.1 seconds.
======
Deploy OK
Use hungarian: False
Begin Tracking

Traceback (most recent call last):
  File "tools/nusc_tracking/pub_test.py", line 190, in <module>
    main()
  File "tools/nusc_tracking/pub_test.py", line 110, in main
    preds = predictions[token]
KeyError: '1b9a789e08bb4b7b89eacb2176c70840'

**Comment by ZhangTingyang** [comment]
help！

**Comment by sayhiOK** [comment]
me too @ZhangTingyang

**Comment by huichen98** [comment]
没有的直接删掉好了

**Comment by ZhangTingyang** [comment]
> 没有的直接跳过

但直接最后一步会报错缺少这个文件infos_test_10sweeps_withvelo_filter_True.pkl，这个应该是在报错的那一步生成的pkl文件吧

**Comment by Feng-ming-wang** [comment]
> 

怎么跳过呀

**Comment by tzy-0716** [comment]
me too! help!

**Comment by justeWang** [comment]
> root@autodl-container-a2b111a626-eef41984:~/autodl-tmp/CenterPoint# python tools/nusc_tracking/pub_test.py --work_dir model --checkpoint work_dirs/result/infos_val_10sweeps_withvelo_filter_True.json --version v1.0-test --root data/nuScenes/v1.0-test
> 
> # ======
> Loading NuScenes tables for version v1.0-test...
> 23 category,
> 8 attribute,
> 4 visibility,
> 0 instance,
> 12 sensor,
> 1800 calibrated_sensor,
> 462901 ego_pose,
> 15 log,
> 150 scene,
> 6008 sample,
> 462901 sample_data,
> 0 sample_annotation,
> 4 map,
> Done loading in 3.7 seconds.
> # Reverse indexing ...
> Done reverse indexing in 1.1 seconds.
> Deploy OK Use hungarian: False Begin Tracking
> 
> Traceback (most recent call last): File "tools/nusc_tracking/pub_test.py", line 190, in main() File "tools/nusc_tracking/pub_test.py", line 110, in main preds = predictions[token] KeyError: '1b9a789e08bb4b7b89eacb2176c70840'

Hello, I also met the same problem, do you remember how to solve it? I am looking for some algorithms for cloud target tracking, or can you give me some suggestions?
您好，我也遇到了相同的问题，请问您还记得怎么解决的吗？我正在找点云目标跟踪的算法，或者您可以给我一下建议吗？
