### ISSUE TITLE
Unable to find  nuScenes devkit

### ISSUE THREAD

**Issue by WyjFrogi** [tianweiy/CenterPoint#406]
Why can't I find the nuScenes devkit, the dataset I'm using is the v1.0-mini nuScenes dataset, but when running the evaluation code I get:
```
python ./tools/dist_test.py ./configs/nusc/voxelnet/nusc_centerpoint_voxelnet_01voxel.py --work_dir work_dirs/nusc_centerpoint_voxelnet_01voxel/ --checkpoint work_dirs/nusc_centerpoint_voxelnet_01voxel/latest.pth --speed_test

No APEX!
~/CenterPoint/det3d/core/bbox/geometry.py:149: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(nopython=False)
~CenterPoint/det3d/core/bbox/geometry.py:162: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(nopython=False)
~/CenterPoint/det3d/core/bbox/geometry.py:279: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
nuScenes devkit not Found!
No Tensorflow
Deformable Convolution not built!
No APEX!
2023-12-20 22:47:39,612 - INFO - Distributed testing: False
2023-12-20 22:47:39,612 - INFO - torch.backends.cudnn.benchmark: False
2023-12-20 22:47:39,681 - INFO - Finish RPN Initialization
2023-12-20 22:47:39,681 - INFO - num_classes: [1, 2, 2, 1, 2, 2]
Use HM Bias:  -2.19
2023-12-20 22:47:39,703 - INFO - Finish CenterHead Initialization
Use Val Set
10
2023-12-20 22:47:40,439 - INFO - work dir: work_dirs/nusc_centerpoint_voxelnet_01voxel/
[                                                  ] 0/81, elapsed: 0s, ETA:/home/wyj/anaconda3/envs/centerpoint/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 7.9 task/s, elapsed: 10s, ETA:     0s
 Total time per frame:  0.09292174268651891
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.3 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.0 seconds.
======
Finish generate predictions for testset, save to work_dirs/nusc_centerpoint_voxelnet_01voxel/infos_val_10sweeps_withvelo_filter_True.json
Traceback (most recent call last):
  File "/home/wyj/CenterPoint/./tools/dist_test.py", line 211, in <module>
    main()
  File "/home/wyj/CenterPoint/./tools/dist_test.py", line 201, in main
    result_dict, _ = dataset.evaluation(copy.deepcopy(predictions), output_dir=args.work_dir, testset=args.testset)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/CenterPoint/det3d/datasets/nuscenes/nuscenes.py", line 292, in evaluation
    eval_main(
  File "~/CenterPoint/det3d/datasets/nuscenes/nusc_common.py", line 614, in eval_main
    nusc_eval = NuScenesEval(
                ^^^^^^^^^^^^
NameError: name 'NuScenesEval' is not defined
```
But I have obviously added nuScenes devkit to the environment variables.

```
❯ echo $PYTHONPATH
:/home/wyj/CenterPoint:/home/wyj/CenterPoint/nuscenes-devkit/python-sdk
```
@triple-tam in https://github.com/tianweiy/CenterPoint/issues/87 i.e.

Thanks!

**Comment by WyjFrogi** [comment]
I have found the cause of the error because I am using python version 3.11 and in 3.11 cannot import name 'Iterable' from 'collections'，but， File "anaconda3/envs/centerpoint/lib/python3.11/site-packages/motmetrics/metrics.py" ，line 9 is ：
```
from collections import OrderedDict, Iterable
```
so, I have changed this code,

**Comment by YangChen1234567** [comment]
Hi！ Have you got the evaluation result of Centerpoint-PP in nusc-mini dataset? I evaluted the checkpoint provided by author in nusc-mini dataset, but the mAP is lower than paper's(mAP is 41, but the value in paper is 50.......). I don't know why....
