### ISSUE TITLE
can't run trainning with multi-GPU

### ISSUE THREAD

**Issue by MengWangTHU** [tianweiy/CenterPoint#57]
Hi tianweiy:
thankyou for sharing your excellent work about centerpoint.
when i try to run a trainning this command "python -m torch.distributed.launch --nproc_per_node=2 ./tools/train.py configs/", errors occure, like this:

```
File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 128, in main
    logger=logger,
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/apis/train.py", line 381, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/trainer/trainer.py", line 538, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/trainer/trainer.py", line 405, in train
    self.model, data_batch, train_mode=True, **kwargs
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/trainer/trainer.py", line 363, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/detectors/point_pillars.py", line 48, in forward
    x = self.extract_feat(data)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/detectors/point_pillars.py", line 23, in extract_feat
    data["features"], data["num_voxels"], data["coors"]
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/readers/pillar_encoder.py", line 153, in forward
    features = pfn(features)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/readers/pillar_encoder.py", line 46, in forward
    x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2, 1).contiguous()
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/apex/parallel/optimized_sync_batchnorm.py", line 85, in forward
    return SyncBatchnormFunction.apply(input, z, self.weight, self.bias, self.running_mean, self.running_var, self.eps, self.training or not self.track_running_stats, exponential_average_factor, self.process_group, channel_last, self.fuse_relu)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/apex/parallel/optimized_sync_batchnorm_kernel.py", line 36, in forward
    torch.distributed.all_gather(mean_l, mean, process_group)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1185, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: All tensor operands to scatter/gather must have the same size

Traceback (most recent call last):
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 128, in main
    logger=logger,
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/apis/train.py", line 381, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/trainer/trainer.py", line 538, in run
    epoch_runner(data_loaders[i], self.epoch, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/trainer/trainer.py", line 405, in train
    self.model, data_batch, train_mode=True, **kwargs
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/torchie/trainer/trainer.py", line 363, in batch_processor_inline
    losses = model(example, return_loss=True)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/detectors/point_pillars.py", line 48, in forward
    x = self.extract_feat(data)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/detectors/point_pillars.py", line 23, in extract_feat
    data["features"], data["num_voxels"], data["coors"]
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/readers/pillar_encoder.py", line 153, in forward
    features = pfn(features)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/l4disk/datasets/guojingsai/pcdet_v1/CenterPoint/det3d/models/readers/pillar_encoder.py", line 46, in forward
    x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2, 1).contiguous()
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/apex/parallel/optimized_sync_batchnorm.py", line 85, in forward
    return SyncBatchnormFunction.apply(input, z, self.weight, self.bias, self.running_mean, self.running_var, self.eps, self.training or not self.track_running_stats, exponential_average_factor, self.process_group, channel_last, self.fuse_relu)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/apex/parallel/optimized_sync_batchnorm_kernel.py", line 36, in forward
    torch.distributed.all_gather(mean_l, mean, process_group)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1185, in all_gather
    work = _default_pg.allgather([tensor_list], [tensor])
RuntimeError: All tensor operands to scatter/gather must have the same size

Traceback (most recent call last):
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/l4/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/l4/anaconda3/envs/centerpoint/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/centerpoint/waymo_centerpoint_pp_car_large.py']' returned non-zero exit status 1.
```

it seames that there are two key problems: "RuntimeError: All tensor operands to scatter/gather must have the same size" and "subprocess.CalledProcessError: Command '['/home/l4/anaconda3/envs/centerpoint/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/centerpoint/waymo_centerpoint_pp_car_large.py']' returned non-zero exit status 1.

have you ever find this errors?

hoping for your helping.
thank you very much!

**Comment by tianweiy** [comment]
Seems a problem with apex. Can you check if single gpu work? Additionally, is your apex version the same as mine in the installation guide? I found more recent version of apex also doesn't work well in my environment

**Comment by MengWangTHU** [comment]
> Seems a problem with apex. Can you check if single gpu work? Additionally, is your apex version the same as mine in the installation guide? I found more recent version of apex also doesn't work well in my environment

than you for your answer.
Single gpu version in my machine works well, and i already get a good result. but multi-GPU just does NOT work.
the version of the key element in my code are:
python 3.6.10
pytorch 1.6.0
apex 0.1
spconv 1.2.1

**Comment by MengWangTHU** [comment]
> Seems a problem with apex. Can you check if single gpu work? Additionally, is your apex version the same as mine in the installation guide? I found more recent version of apex also doesn't work well in my environment

hi tianweiy:
according to a describtion below: 
https://github.com/rwightman/efficientdet-pytorch/issues/69
the problem maybe occour with torch version=1.6, so could you please list your torch version as you can run multi-GPU trainning.
thanks a lot!

**Comment by tianweiy** [comment]
I use torch 1.1 thanks

**Comment by tianweiy** [comment]
Additionally, you can try newer apex version? Not sure which one work, but it should be quick.

**Comment by MengWangTHU** [comment]
I update my apex to the latest version. and somethting strange happens. 
The programme stops at:
`def points_in_convex_polygon_jit(points, polygon, clockwise=True):
    <source elided>
    # first convert polygon to directed lines
    num_points_of_polygon = polygon.shape[1]
    ^

  state.func_ir.loc))
`
it nerver step forward for tens minutes. 
does anynoe happend to know the problem?

**Comment by tianweiy** [comment]
Can you show me the full stack trace? Where did it get into this func ?

**Comment by MengWangTHU** [comment]
atfer tracking into the code, i find it locked at this scritpt:
det3d/torchie/trainer/trainer.py
and in func:
 batch_processor_inline
more detaild: this----> losses = model(example, return_loss=True)
after this, i didn't go on, but it seems the problem occure when the model process the datas.

A news which is not so bad is that, after I tried a lot  Combination of batch size (samples_per_gpu, in config file) and count of gpus(nproc_per_node), i find it works only when samples_per_gpu=4 and nproc_per_node=2. Other Combination like 4-4 8-2 8-4, just don't work.
It is so WEIRD， but it just works.

**Comment by tianweiy** [comment]
This is weird. Any configuration works in my setting.  

You can also try torch 1.1 if it is easy to set up

**Comment by tianweiy** [comment]
I also noticed the program stops when compiling the numba jit code at the beginning. However, they do recover later so you can probably wait a bit later (30minutes or so?)

**Comment by tianweiy** [comment]
@MengWangTHU Hope the problem is solved. I just update the codebase. Let me know if you face any problems

**Comment by YoushaaMurhij** [comment]
@tianweiy , I have a question related to the batch size and how batch is happening. In nuScenes, every scene is 20s. when we choose a batch size more than one on multiple GPUs. this means that we are not feeding the point clouds in sequence (in there order in the scene), right ?

**Comment by tianweiy** [comment]
yeah, it is random. it is not in a sequence

**Comment by YoushaaMurhij** [comment]
can we edit the dataloader to make it sequential even if more than one patch is used (for tracking task)?

**Comment by tianweiy** [comment]
I don't quite understand the exact use case. Could you elaborate a bit more? You can also send me an email for in-depth discussion
