### ISSUE TITLE
AssertionError: Cannot find metric pred_frequencies required by num_predictions.

### ISSUE THREAD

**Issue by ChenWenming1995** [tianweiy/CenterPoint#61]
Hi tianweiy:
Thanks for your open source code and great work.
When I try to track the detections by running pub_test.py, a wierd error happends like:

Traceback (most recent call last):                                                                                                                                                                     
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dlab/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/dlab/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/dlab/.vscode-server/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dlab/CenterPoint/tools/tracking/pub_test.py", line 199, in <module>
    eval_tracking()
  File "/home/dlab/CenterPoint/tools/tracking/pub_test.py", line 164, in eval_tracking
    eval(os.path.join(args.work_dir, 'tracking_result.json'),
  File "/home/dlab/CenterPoint/tools/tracking/pub_test.py", line 185, in eval
    metrics_summary = nusc_eval.main()
  File "/home/dlab/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py", line 205, in main
    metrics, metric_data_list = self.evaluate()
  File "/home/dlab/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py", line 135, in evaluate
    accumulate_class(class_name)
  File "/home/dlab/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/evaluate.py", line 131, in accumulate_class
    curr_md = curr_ev.accumulate()
  File "/home/dlab/CenterPoint/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/algo.py", line 140, in accumulate
    thresh_summary = mh.compute(acc, metrics=MOT_METRIC_MAP.keys(), name=thresh_name)
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/site-packages/motmetrics/metrics.py", line 185, in compute
    cache[mname] = self._compute(df_map, mname, cache, options, parent='summarize')
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/site-packages/motmetrics/metrics.py", line 310, in _compute
    v = cache[depname] = self._compute(df_map, depname, cache, options, parent=name)
  File "/home/dlab/anaconda3/envs/centerpoint/lib/python3.8/site-packages/motmetrics/metrics.py", line 301, in _compute
    assert name in self.metrics, 'Cannot find metric {} required by {}.'.format(name, parent)
AssertionError: Cannot find metric pred_frequencies required by num_predictions.

Function `save_first_frame()` and `main()` are done. Error occurs in `eval_tracking()`. And the used files are downloaded in google driver.

Have you ever meet this errors?
Hoping for your helping.
Thank you very much!

**Comment by tianweiy** [comment]
if main is done, the tracking algorithm is finished. 

This is a problem with your motmetrics library, see [this](https://github.com/nutonomy/nuscenes-devkit/pull/300/files). Let me know if this still doesn't work

**Comment by ChenWenming1995** [comment]
Thanks a lot. It works.
