### ISSUE TITLE
CenterHead is not in the head registry

### ISSUE THREAD

**Issue by tung-nd** [tianweiy/CenterPoint#66]
When I run single_inference.py using Voxelnet pretrained model, this error message popped up: "CenterHead is not in the head registry", which seems to be a problem from det3d. Can you please help?

**Comment by tianweiy** [comment]
is the demo in the README work? This is just some path issue.

**Comment by tianweiy** [comment]
Also, please paste all commands and all outputs.

**Comment by tung-nd** [comment]
My command is `python single_inference.py` from the `tools` directory
Here is the output:
Traceback (most recent call last):
  File "single_infernece.py", line 249, in <module>
    proc_1.initialize()
  File "single_infernece.py", line 92, in initialize
    self.read_config()
  File "single_infernece.py", line 98, in read_config
    self.net = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/home/ubuntu/Det3D/det3d/models/builder.py", line 53, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/ubuntu/Det3D/det3d/models/builder.py", line 21, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/Det3D/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/home/ubuntu/Det3D/det3d/models/detectors/voxelnet.py", line 18, in __init__
    reader, backbone, neck, bbox_head, train_cfg, test_cfg, pretrained
  File "/home/ubuntu/Det3D/det3d/models/detectors/single_stage.py", line 25, in __init__
    self.bbox_head = builder.build_head(bbox_head)
  File "/home/ubuntu/Det3D/det3d/models/builder.py", line 45, in build_head
    return build(cfg, HEADS)
  File "/home/ubuntu/Det3D/det3d/models/builder.py", line 21, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/Det3D/det3d/utils/registry.py", line 66, in build_from_cfg
    "{} is not in the {} registry".format(obj_type, registry.name)
KeyError: 'CenterHead is not in the head registry'

**Comment by tianweiy** [comment]
Please add CenterPoint into your python path. Currently it is using the box head in the det3d library
