### ISSUE TITLE
error at begining of waymo training

### ISSUE THREAD

**Issue by hz3014** [tianweiy/CenterPoint#90]
way to produce error:
_python -m torch.distributed.launch --nproc_per_node=8 ./tools/train.py configs/waymo/pp/waymo_centerpoint_pp_two_pfn_stride1_3x.py_

files under data/Waymo:
_dbinfos_train_1sweeps_withvelo.pkl   
 tfrecord_validation
gt_database_1sweeps_withvelo    
             train
infos_train_01sweeps_filter_zero_gt.pkl   
    val
infos_val_01sweeps_filter_zero_gt.pkl_

I guess tfrecord_test is not necessary for training?

error message:
Finish CenterHead Initialization
Using 1 sweeps
Using 158361 Frames
_Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 112, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mnt/CenterPoint/det3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/mnt/CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/CenterPoint/det3d/datasets/waymo/waymo.py", line 40, in __init__
    root_path, info_path, pipeline, test_mode=test_mode, class_names=class_names
  File "/mnt/CenterPoint/det3d/datasets/custom.py", line 42, in __init__
    self.pipeline = Compose(pipeline)
  File "/mnt/CenterPoint/det3d/datasets/pipelines/compose.py", line 16, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/mnt/CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/CenterPoint/det3d/datasets/pipelines/preprocess.py", line 39, in __init__
    self.db_sampler = build_dbsampler(cfg.db_sampler)
  File "/mnt/CenterPoint/det3d/builder.py", line 219, in build_dbsampler
    db_infos, groups, db_prepor, rate, grot_range, logger=logger
  File "/mnt/CenterPoint/det3d/core/sampler/sample_ops.py", line 27, in __init__
    db_infos = db_prepor(db_infos)
  File "/mnt/CenterPoint/det3d/core/sampler/preprocess.py", line 104, in __call__
    db_infos = prepor(db_infos)
  File "/mnt/CenterPoint/det3d/core/sampler/preprocess.py", line 59, in __call__
    return self._preprocess(db_infos)
  File "/mnt/CenterPoint/det3d/core/sampler/preprocess.py", line 91, in _preprocess
    for info in db_infos[name]:
KeyError: 'VEHICLE'
Traceback (most recent call last):
  File "/home/user5/.conda/envs/centerpoint/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user5/.conda/envs/centerpoint/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user5/.conda/envs/centerpoint/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/user5/.conda/envs/centerpoint/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/user5/.conda/envs/centerpoint/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/waymo/pp/waymo_centerpoint_pp_two_pfn_stride1_3x.py']' returned non-zero exit status 1.__

Thanks in advance!

**Comment by tianweiy** [comment]
> I guess tfrecord_test is not necessary for training?

not necessary 

This is a problem with the gt database for augmentation. Could you check your db_infos file? It should get three keys dict_keys(['VEHICLE', 'PEDESTRIAN', 'CYCLIST'])


and then when you start training, you should see something like this 

2021-03-03 20:59:47,640 - INFO - {'VEHICLE': 5, 'PEDESTRIAN': 5, 'CYCLIST': 5}
2021-03-03 20:59:47,641 - INFO - [-1]
2021-03-03 20:59:57,769 - INFO - load 1088225 VEHICLE database infos
2021-03-03 20:59:57,769 - INFO - load 1018824 PEDESTRIAN database infos
2021-03-03 20:59:57,769 - INFO - load 49518 CYCLIST database infos
2021-03-03 21:00:01,081 - INFO - After filter database:
2021-03-03 21:00:01,083 - INFO - load 1020390 VEHICLE database infos
2021-03-03 21:00:01,083 - INFO - load 948485 PEDESTRIAN database infos
2021-03-03 21:00:01,084 - INFO - load 47534 CYCLIST database infos

**Comment by hz3014** [comment]
@tianweiy I got relevant error message:
 2021-03-04 11:56:13,125 - INFO - {'VEHICLE': 5, 'PEDESTRIAN': 5, 'CYCLIST': 5}
2021-03-04 11:56:13,126 - INFO - [-1]
Traceback (most recent call last):
  File "./tools/train.py", line 137, in <module>
    main()
  File "./tools/train.py", line 112, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/datasets/waymo/waymo.py", line 40, in __init__
    root_path, info_path, pipeline, test_mode=test_mode, class_names=class_names
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/datasets/custom.py", line 42, in __init__
    self.pipeline = Compose(pipeline)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/datasets/pipelines/compose.py", line 16, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/datasets/pipelines/preprocess.py", line 39, in __init__
    self.db_sampler = build_dbsampler(cfg.db_sampler)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/builder.py", line 219, in build_dbsampler
    db_infos, groups, db_prepor, rate, grot_range, logger=logger
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/core/sampler/sample_ops.py", line 27, in __init__
    db_infos = db_prepor(db_infos)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/core/sampler/preprocess.py", line 104, in __call__
    db_infos = prepor(db_infos)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/core/sampler/preprocess.py", line 59, in __call__
    return self._preprocess(db_infos)
  File "/mnt/lvm/root/public_storage/zhouH/CenterPoint/det3d/core/sampler/preprocess.py", line 91, in _preprocess
    for info in db_infos[name]:

I guess something wrong in _python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split train --nsweeps=1_  but hard to spot the cause of problem

**Comment by tianweiy** [comment]
let me check

**Comment by tianweiy** [comment]
what is your output when running create_data.py is your dataset the whole waymo. You should see sth like 

train  split  exist frame num: 199
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 1841.36it/s]
sample: 199
Using 1 sweeps
Using 199 Frames
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:04<00:00, 40.33it/s]
dataset length:  199
load 505 VEHICLE database infos
load 196 PEDESTRIAN database infos

**Comment by tianweiy** [comment]
> @tianweiy I got relevant error message:
> 2021-03-04 11:56:13,125 - INFO - {'VEHICLE': 5, 'PEDESTRIAN': 5, 'CYCLIST': 5}
> 2021-03-04 11:56:13,126 - INFO - [-1]
> Traceback (most recent call last):
> File "./tools/train.py", line 137, in
> main()
> File "./tools/train.py", line 112, in main
> datasets = [build_dataset(cfg.data.train)]
> File "/mnt/CenterPoint/det3d/datasets/builder.py", line 41, in build_dataset
> dataset = build_from_cfg(cfg, DATASETS, default_args)
> File "/mnt//CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
> return obj_cls(**args)
> File "/mnt/CenterPoint/det3d/datasets/waymo/waymo.py", line 40, in **init**
> root_path, info_path, pipeline, test_mode=test_mode, class_names=class_names
> File "/mnt/CenterPoint/det3d/datasets/custom.py", line 42, in **init**
> self.pipeline = Compose(pipeline)
> File "/mnt/CenterPoint/det3d/datasets/pipelines/compose.py", line 16, in **init**
> transform = build_from_cfg(transform, PIPELINES)
> File "/mnt/CenterPoint/det3d/utils/registry.py", line 78, in build_from_cfg
> return obj_cls(**args)
> File "/mnt/CenterPoint/det3d/datasets/pipelines/preprocess.py", line 39, in **init**
> self.db_sampler = build_dbsampler(cfg.db_sampler)
> File "/mnt/CenterPoint/det3d/builder.py", line 219, in build_dbsampler
> db_infos, groups, db_prepor, rate, grot_range, logger=logger
> File "/mnt/CenterPoint/det3d/core/sampler/sample_ops.py", line 27, in **init**
> db_infos = db_prepor(db_infos)
> File "/mnt/CenterPoint/det3d/core/sampler/preprocess.py", line 104, in **call**
> db_infos = prepor(db_infos)
> File "/mnt/CenterPoint/det3d/core/sampler/preprocess.py", line 59, in **call**
> return self._preprocess(db_infos)
> File "/mnt/CenterPoint/det3d/core/sampler/preprocess.py", line 91, in _preprocess
> for info in db_infos[name]:
> 
> I guess something wrong in _python tools/create_data.py waymo_data_prep --root_path=data/Waymo --split train --nsweeps=1_ but hard to spot the cause of problem

could you just check your dbinfos.pkl file, is there vehicle in it? It is possible that your dataset may not have vehicles ...

**Comment by hz3014** [comment]
@tianweiy I think it is indeed the case when no groundtruth generated. My Waymo dataset consists all 31 tar file but it was downloaded a year ago. Same dataset was successfully training the PVRCNN repo. Do you think i need to redownload dataset?
train  split  exist frame num: 158361
100%|█████████████████████████████████| 158361/158361 [02:34<00:00, 1025.58it/s]
sample: 158361
Using 1 sweeps
Using 158361 Frames
100%|███████████████████████████████████| 158361/158361 [30:57<00:00, 85.24it/s]
dataset length:  158361

Would you also take a look at my _CUDA_VISIBLE_DEVICES=-1 python det3d/datasets/waymo/waymo_converter.py --record_path '/media/2TB/WAYMO_DATASET_ROOT/tfrecord_training/segment-*.tfrecord'  --root_path '/media/2TB/WAYMO_DATASET_ROOT/train/'_
there is a lot werid messages:
2021-03-02 11:57:51.120765: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-03-02 11:57:51.121508: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2021-03-02 11:57:51.122044: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e84a1eb7c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-02 11:57:51.122080: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
100%|████████████████████████████████| 798/798 [21:21:22<00:00, 96.34s/it]

**Comment by tianweiy** [comment]
> Do you think i need to redownload dataset

No, I don't think it gets much difference. 

Could you send any annotation files in the converted dataset? From here CenterPoint/data/Waymo/train/annos/seq_XXX_frame_XXX.pkl

**Comment by hz3014** [comment]
@tianweiy sent to your email

**Comment by tianweiy** [comment]
Yeah, I am checking.

**Comment by hz3014** [comment]
The issue was basically caused by outdated waymo dataset. Redownload dataset would fix the issue. Tried other methods as @tianweiy suggested. Prebuild pkl didnt work as the dataset difference is up to file name level.
